/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.ijse.fms.view.panel;

import edu.ijse.fms.common.IDGenerator;
import edu.ijse.fms.controller.ControllerFactory;
import edu.ijse.fms.controller.custom.CustomerController;
import edu.ijse.fms.db.ConnectionFactory;
import edu.ijse.fms.dto.CustomerDTO;
import edu.ijse.fms.view.SearchCustomerDialog;
import java.awt.Color;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.border.Border;
import javax.swing.border.LineBorder;

/**
 *
 * @author Gnanod
 */
public class CustomerPanel extends javax.swing.JPanel {

    private CustomerController customerController;

    /**
     * Creates new form CustomerPanel
     */
    public CustomerPanel() {
        initComponents();
        customerController = (CustomerController) ControllerFactory.getInstance().getController(ControllerFactory.ControllerTypes.CUSTOMER);
        getID();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel27 = new javax.swing.JLabel();
        txtCustomerId = new javax.swing.JTextField();
        txtCustomerName = new javax.swing.JTextField();
        btnCustomerMale = new javax.swing.JRadioButton();
        btnCustomerFemale = new javax.swing.JRadioButton();
        txtCustomerTelNumber = new javax.swing.JTextField();
        txtCustomerAddress = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        btnCustomerSave = new javax.swing.JLabel();
        btnCustomerUpdate = new javax.swing.JLabel();
        btnCustomerDelete = new javax.swing.JLabel();
        btnCustomerSearch1 = new javax.swing.JLabel();
        jXLabel1 = new org.jdesktop.swingx.JXLabel();
        jLabel8 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1070, 660));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel27.setBackground(new java.awt.Color(255, 255, 255));
        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(53, 126, 120));
        jLabel27.setText("                        Manage Customer");
        jLabel27.setToolTipText("");
        jLabel27.setOpaque(true);
        add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 0, 770, 50));

        txtCustomerId.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtCustomerId.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtCustomerId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCustomerIdActionPerformed(evt);
            }
        });
        txtCustomerId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCustomerIdKeyReleased(evt);
            }
        });
        add(txtCustomerId, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 70, 400, 40));

        txtCustomerName.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtCustomerName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtCustomerName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCustomerNameActionPerformed(evt);
            }
        });
        txtCustomerName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCustomerNameKeyReleased(evt);
            }
        });
        add(txtCustomerName, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 120, 400, 40));

        btnCustomerMale.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(btnCustomerMale);
        btnCustomerMale.setSelected(true);
        btnCustomerMale.setText("Male");
        add(btnCustomerMale, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 180, 130, -1));

        btnCustomerFemale.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(btnCustomerFemale);
        btnCustomerFemale.setText("Female");
        add(btnCustomerFemale, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 180, 130, -1));

        txtCustomerTelNumber.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtCustomerTelNumber.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtCustomerTelNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCustomerTelNumberActionPerformed(evt);
            }
        });
        txtCustomerTelNumber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCustomerTelNumberKeyReleased(evt);
            }
        });
        add(txtCustomerTelNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 220, 400, 40));

        txtCustomerAddress.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtCustomerAddress.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtCustomerAddress.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCustomerAddressKeyReleased(evt);
            }
        });
        add(txtCustomerAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 270, 400, 40));

        jLabel23.setBackground(new java.awt.Color(255, 255, 255));
        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(27, 157, 175));
        jLabel23.setText("          Address");
        jLabel23.setToolTipText("");
        jLabel23.setOpaque(true);
        jLabel23.setRequestFocusEnabled(false);
        add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 270, 260, 40));

        jLabel22.setBackground(new java.awt.Color(255, 255, 255));
        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(27, 157, 175));
        jLabel22.setText("          Tel Number");
        jLabel22.setToolTipText("");
        jLabel22.setOpaque(true);
        jLabel22.setRequestFocusEnabled(false);
        add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 220, 260, 40));

        jLabel21.setBackground(new java.awt.Color(255, 255, 255));
        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(27, 157, 175));
        jLabel21.setText("          Gender");
        jLabel21.setToolTipText("");
        jLabel21.setOpaque(true);
        jLabel21.setRequestFocusEnabled(false);
        add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, 260, 40));

        jLabel19.setBackground(new java.awt.Color(255, 255, 255));
        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(27, 157, 175));
        jLabel19.setText("          Customer Name");
        jLabel19.setToolTipText("");
        jLabel19.setOpaque(true);
        jLabel19.setRequestFocusEnabled(false);
        add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, 260, 40));

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(27, 157, 175));
        jLabel12.setText("          Customer Id");
        jLabel12.setToolTipText("");
        jLabel12.setOpaque(true);
        jLabel12.setRequestFocusEnabled(false);
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 260, 40));

        btnCustomerSave.setBackground(new java.awt.Color(255, 255, 255));
        btnCustomerSave.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnCustomerSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/ijse/fms/images/Add User Male_26px.png"))); // NOI18N
        btnCustomerSave.setText("    Add");
        btnCustomerSave.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(27, 157, 175)));
        btnCustomerSave.setOpaque(true);
        btnCustomerSave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCustomerSaveMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCustomerSaveMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCustomerSaveMouseExited(evt);
            }
        });
        add(btnCustomerSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 480, 120, 60));

        btnCustomerUpdate.setBackground(new java.awt.Color(255, 255, 255));
        btnCustomerUpdate.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnCustomerUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/ijse/fms/images/Change User Male_26px.png"))); // NOI18N
        btnCustomerUpdate.setText("    Update");
        btnCustomerUpdate.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(27, 157, 175)));
        btnCustomerUpdate.setOpaque(true);
        btnCustomerUpdate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCustomerUpdateMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCustomerUpdateMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCustomerUpdateMouseExited(evt);
            }
        });
        add(btnCustomerUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 480, 120, 60));

        btnCustomerDelete.setBackground(new java.awt.Color(255, 255, 255));
        btnCustomerDelete.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnCustomerDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/ijse/fms/images/Remove User Male_26px.png"))); // NOI18N
        btnCustomerDelete.setText("     Delete");
        btnCustomerDelete.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(27, 157, 175)));
        btnCustomerDelete.setOpaque(true);
        btnCustomerDelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCustomerDeleteMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCustomerDeleteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCustomerDeleteMouseExited(evt);
            }
        });
        add(btnCustomerDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 480, 120, 60));

        btnCustomerSearch1.setBackground(new java.awt.Color(255, 255, 255));
        btnCustomerSearch1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnCustomerSearch1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/ijse/fms/images/Find User Male_26px.png"))); // NOI18N
        btnCustomerSearch1.setText("    Search");
        btnCustomerSearch1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(27, 157, 175)));
        btnCustomerSearch1.setOpaque(true);
        btnCustomerSearch1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCustomerSearch1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCustomerSearch1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCustomerSearch1MouseExited(evt);
            }
        });
        add(btnCustomerSearch1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 480, 120, 60));

        jXLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jXLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(40, 202, 204), 2));
        jXLabel1.setOpaque(true);
        add(jXLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 450, 760, 110));

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setOpaque(true);
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1070, 660));
    }// </editor-fold>//GEN-END:initComponents

    private void txtCustomerIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCustomerIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCustomerIdActionPerformed

    private void txtCustomerNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCustomerNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCustomerNameActionPerformed

    private void txtCustomerTelNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCustomerTelNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCustomerTelNumberActionPerformed

    private void btnCustomerSaveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCustomerSaveMouseClicked
        String customerId = txtCustomerId.getText();
        String customerName = txtCustomerName.getText();
        String customerGender = "male";

        if (btnCustomerMale.isSelected()) {
            customerGender = "male";
        }
        if (btnCustomerFemale.isSelected()) {
            customerGender = "Female";
        }
        String customerTelNumber = txtCustomerTelNumber.getText();
        String customerAddress = txtCustomerAddress.getText();
        CustomerDTO customerDto = new CustomerDTO(customerId, customerName, customerGender, customerTelNumber, customerAddress);
        if (customerId.isEmpty()) {
            txtCustomerId.setBorder(new LineBorder(Color.red, 1));
        }
        if (customerName.isEmpty()) {
            txtCustomerName.setBorder(new LineBorder(Color.red, 1));
        }
        if (!customerTelNumber.matches("\\d{3}-\\d{7}")) {
            txtCustomerTelNumber.setBorder(new LineBorder(Color.red, 1));
        }
        if (customerAddress.isEmpty()) {
            txtCustomerAddress.setBorder(new LineBorder(Color.red, 1));
        }
        if (customerId.isEmpty() == false && customerName.isEmpty() == false && customerTelNumber.matches("\\d{3}-\\d{7}") == false && customerAddress.isEmpty() == false) {
            try {
                boolean isAdded = customerController.add(customerDto);
                System.out.println(isAdded);
                if (isAdded) {
                    JOptionPane.showMessageDialog(this, "Added Sucessfully");
                    textFieldNull();
                    getID();
                } else {
                    JOptionPane.showMessageDialog(this, "Oops Added Fail", "Error", JOptionPane.ERROR_MESSAGE);
                }
            } catch (SQLException ex) {
                String errorMsg;
                switch (ex.getErrorCode()){
                    case 1062:
                        errorMsg = "Duplicate entry has been found. Please enter valid Customer Id to proceed.";
                        break;
                    default:
                        errorMsg = "Customer has been failed to add";
                        break;
                }
                JOptionPane.showMessageDialog(this, errorMsg, "Error", JOptionPane.ERROR_MESSAGE);

            } catch (Exception ex) {
                Logger.getLogger(CustomerPanel.class.getName()).log(Level.SEVERE, null, ex);
            }

        }


    }//GEN-LAST:event_btnCustomerSaveMouseClicked

    private void btnCustomerSearch1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCustomerSearch1MouseClicked

        SearchCustomerDialog customer = new  SearchCustomerDialog(null, true,this);
        customer.setVisible(true);
    }//GEN-LAST:event_btnCustomerSearch1MouseClicked

    private void btnCustomerUpdateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCustomerUpdateMouseClicked
        String customerId = txtCustomerId.getText();
        String customerName = txtCustomerName.getText();
        String supplierGender = "Male";
        if (btnCustomerMale.isSelected()) {
            supplierGender = "Male";
        }
        if (btnCustomerMale.isSelected()) {
            supplierGender = "Female";
        }
        String address = txtCustomerAddress.getText();
        String telNumber = txtCustomerTelNumber.getText();
        CustomerDTO customerDto = new CustomerDTO(customerId, customerName, supplierGender, telNumber,address);
        try {
            boolean isUpdated = customerController.update(customerDto);
            if (isUpdated) {
                JOptionPane.showMessageDialog(this, "Updated sucessfully");

            } else {
                JOptionPane.showMessageDialog(this, "Oops Added Fail", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (SQLException ex) {
            String errorMsg;
            switch (ex.getErrorCode()) {
                case 1062:
                    errorMsg = "Duplicate entry has been found. Please enter valid Customer Id to proceed.";
                    break;
                default:
                    errorMsg = "Customer has been failed to add";
                    break;
            }
            JOptionPane.showMessageDialog(this, errorMsg, "Error", JOptionPane.ERROR_MESSAGE);

        } catch (Exception ex) {
            Logger.getLogger(CustomerPanel.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnCustomerUpdateMouseClicked

    private void btnCustomerDeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCustomerDeleteMouseClicked
        String id = txtCustomerId.getText();
        try {
            boolean isDeleted = customerController.delete(id);
            if (isDeleted) {
                JOptionPane.showMessageDialog(this, "Supplier is deleted");
            } else {
                JOptionPane.showMessageDialog(this, "Deleted Fail");
            }
        } catch (Exception ex) {
            Logger.getLogger(CustomerPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnCustomerDeleteMouseClicked

    private void txtCustomerIdKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCustomerIdKeyReleased
        String id = txtCustomerId.getText();
        if(id.isEmpty()){
          txtCustomerId.setBorder(new LineBorder(Color.red, 1));
      }else{
          txtCustomerId.setBorder(new LineBorder(Color.black, 1));
      }
    }//GEN-LAST:event_txtCustomerIdKeyReleased

    private void txtCustomerNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCustomerNameKeyReleased
            String name = txtCustomerName.getText();
            if(name.isEmpty()){
                txtCustomerName.setBorder(new LineBorder(Color.red,1));
            }else{
                txtCustomerName.setBorder(new LineBorder(Color.black, 1));
            }
    }//GEN-LAST:event_txtCustomerNameKeyReleased

    private void txtCustomerTelNumberKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCustomerTelNumberKeyReleased
            String telNumber = txtCustomerTelNumber.getText();
            if(!telNumber.matches("\\b\\d{3}-\\d{7}\\b")){
                txtCustomerTelNumber.setBorder(new LineBorder(Color.red,1));
            }else{
                txtCustomerTelNumber.setBorder(new LineBorder(Color.black, 1));
            }
            
    }//GEN-LAST:event_txtCustomerTelNumberKeyReleased

    private void txtCustomerAddressKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCustomerAddressKeyReleased
            String address = txtCustomerAddress.getText();
            if(address.isEmpty()){
                txtCustomerAddress.setBorder(new LineBorder(Color.red,1));
            }else{
                txtCustomerAddress.setBorder(new LineBorder(Color.black, 1));
            }
    }//GEN-LAST:event_txtCustomerAddressKeyReleased

    private void btnCustomerSaveMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCustomerSaveMouseEntered
        btnCustomerSave.setBackground(new Color(40, 202, 204));
    }//GEN-LAST:event_btnCustomerSaveMouseEntered

    private void btnCustomerSaveMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCustomerSaveMouseExited
        btnCustomerSave.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_btnCustomerSaveMouseExited

    private void btnCustomerSearch1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCustomerSearch1MouseEntered
       btnCustomerSearch1.setBackground(new Color(40, 202, 204));
    }//GEN-LAST:event_btnCustomerSearch1MouseEntered

    private void btnCustomerSearch1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCustomerSearch1MouseExited
       btnCustomerSearch1.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_btnCustomerSearch1MouseExited

    private void btnCustomerUpdateMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCustomerUpdateMouseEntered
        btnCustomerUpdate.setBackground(new Color(40, 202, 204));
    }//GEN-LAST:event_btnCustomerUpdateMouseEntered

    private void btnCustomerDeleteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCustomerDeleteMouseEntered
       btnCustomerDelete.setBackground(new Color(40, 202, 204));
    }//GEN-LAST:event_btnCustomerDeleteMouseEntered

    private void btnCustomerUpdateMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCustomerUpdateMouseExited
        btnCustomerUpdate.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_btnCustomerUpdateMouseExited

    private void btnCustomerDeleteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCustomerDeleteMouseExited
       btnCustomerDelete.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_btnCustomerDeleteMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnCustomerDelete;
    private javax.swing.JRadioButton btnCustomerFemale;
    private javax.swing.JRadioButton btnCustomerMale;
    private javax.swing.JLabel btnCustomerSave;
    private javax.swing.JLabel btnCustomerSearch1;
    private javax.swing.JLabel btnCustomerUpdate;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel8;
    private org.jdesktop.swingx.JXLabel jXLabel1;
    private javax.swing.JTextField txtCustomerAddress;
    private javax.swing.JTextField txtCustomerId;
    private javax.swing.JTextField txtCustomerName;
    private javax.swing.JTextField txtCustomerTelNumber;
    // End of variables declaration//GEN-END:variables
private void getID() {
        String newID;
        try {
            newID = IDGenerator.getNewID("customer", "CustId", "c");
            txtCustomerId.setText(newID);

        } catch (ClassNotFoundException | SQLException e) {
        }
    }

    private void textFieldNull() {
        txtCustomerName.setText(null);
        txtCustomerTelNumber.setText(null);
        txtCustomerAddress.setText(null);
    }

    public void setCustomerDetails(CustomerDTO c1) {
        txtCustomerId.setText(c1.getCustomerId());
        txtCustomerName.setText(c1.getCustomerName());
        txtCustomerTelNumber.setText(c1.getCustomerTelNumber());
        String gender = c1.getCustomerGender();

        if (gender.equals("Male")) {

            btnCustomerMale.setSelected(true);

        } else {

            btnCustomerFemale.setSelected(true);

        }

        txtCustomerAddress.setText(c1.getCustomerAddress());
       
    }
}
