/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.ijse.fms.view.panel;

import edu.ijse.fms.controller.ControllerFactory;
import edu.ijse.fms.controller.custom.ValubleCustomerController;
import edu.ijse.fms.dto.ValubleCustomerDTO;
import java.awt.Color;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Gnanod
 */
public class CustomerPayment extends javax.swing.JPanel {

    /**
     * Creates new form CustomerPayment
     */
    private ValubleCustomerController valubleCustomer;
    private DefaultTableModel dtm;
    public CustomerPayment(){
        initComponents();
        valubleCustomer = (ValubleCustomerController) ControllerFactory.getInstance().getController(ControllerFactory.ControllerTypes.VALUBLECUSTOMER);
        dtm = (DefaultTableModel) tblCustomer.getModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel50 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCustomer = new javax.swing.JTable();
        btnDelete = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel51 = new javax.swing.JLabel();
        txtDesc = new javax.swing.JTextField();
        jLabel52 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel50.setBackground(new java.awt.Color(255, 255, 255));
        jLabel50.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel50.setForeground(new java.awt.Color(53, 126, 120));
        jLabel50.setText("Maximun GrocessAmount");
        jLabel50.setToolTipText("");
        jLabel50.setOpaque(true);
        add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 50, 240, 30));

        tblCustomer.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CustomerName", "Date", "GrocessAmount", "Address", "Telephone Number"
            }
        ));
        jScrollPane1.setViewportView(tblCustomer);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 930, 180));

        btnDelete.setBackground(new java.awt.Color(255, 255, 255));
        btnDelete.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/ijse/fms/images/print 1.png"))); // NOI18N
        btnDelete.setText("   Print");
        btnDelete.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(27, 157, 175)));
        btnDelete.setOpaque(true);
        btnDelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDeleteMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDeleteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDeleteMouseExited(evt);
            }
        });
        add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 280, 110, 30));
        add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 90, 190, 30));

        jLabel51.setBackground(new java.awt.Color(255, 255, 255));
        jLabel51.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel51.setForeground(new java.awt.Color(53, 126, 120));
        jLabel51.setText("                          Most Valuble customer");
        jLabel51.setToolTipText("");
        jLabel51.setOpaque(true);
        add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 0, 780, 50));

        txtDesc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDescActionPerformed(evt);
            }
        });
        add(txtDesc, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, 190, 30));

        jLabel52.setBackground(new java.awt.Color(255, 255, 255));
        jLabel52.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel52.setForeground(new java.awt.Color(53, 126, 120));
        jLabel52.setText("Minimum GrocessAmount");
        jLabel52.setToolTipText("");
        jLabel52.setOpaque(true);
        add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, 240, 30));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setOpaque(true);
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1070, 670));
    }// </editor-fold>//GEN-END:initComponents

    private void btnDeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeleteMouseClicked
        
    }//GEN-LAST:event_btnDeleteMouseClicked

    private void btnDeleteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeleteMouseEntered
        btnDelete.setBackground(new Color(40, 202, 204));
    }//GEN-LAST:event_btnDeleteMouseEntered

    private void btnDeleteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeleteMouseExited
        btnDelete.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_btnDeleteMouseExited

    private void txtDescActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDescActionPerformed
        try {
            int number = Integer.parseInt(txtDesc.getText());
            ArrayList<ValubleCustomerDTO>customer = valubleCustomer.serchNumber(number);
            for (ValubleCustomerDTO customer1 : customer) {
                Object [] rowData = {customer1.getCustomerName(),customer1.getDate(),customer1.getGrocessAmount(),customer1.getAddress(),customer1.getTelePhoneNumber()};
                
                dtm.addRow(rowData);
            }
        } catch (Exception ex) {
            Logger.getLogger(CustomerPayment.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_txtDescActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnDelete;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTable tblCustomer;
    private javax.swing.JTextField txtDesc;
    // End of variables declaration//GEN-END:variables

    
    
}
