/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.ijse.fms.view.panel;

import edu.ijse.fms.controller.ControllerFactory;
import edu.ijse.fms.controller.custom.BatchController;
import edu.ijse.fms.controller.custom.ItemNameBatchIdController;
import edu.ijse.fms.controller.custom.ViewItemNameBatchController;
import edu.ijse.fms.dto.BatchDTO;
import edu.ijse.fms.dto.ItemNameBatchIdDTO;
import edu.ijse.fms.dto.ViewItemNameBatchDTO;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Gnanod
 */
public class pnlViewAllItem extends javax.swing.JPanel {

    /**
     * Creates new form pnlViewAllItem
     */
    private BatchController batchController;
    private ViewItemNameBatchController viewItemNameBatchController;
    private DefaultTableModel dtm;
    public pnlViewAllItem() {
        initComponents();
    viewAllItems();
        viewItemNameBatchController = (ViewItemNameBatchController) ControllerFactory.getInstance().getController(ControllerFactory.ControllerTypes.ITEMNAMEBATCH);
        dtm = (DefaultTableModel) tblItem.getModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel34 = new javax.swing.JLabel();
        txtSearchSupplier = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblItem = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel34.setBackground(new java.awt.Color(255, 255, 255));
        jLabel34.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(53, 126, 120));
        jLabel34.setText("                                  View All Items");
        jLabel34.setToolTipText("");
        jLabel34.setOpaque(true);
        add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 0, 770, 50));

        txtSearchSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchSupplierActionPerformed(evt);
            }
        });
        txtSearchSupplier.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchSupplierKeyReleased(evt);
            }
        });
        add(txtSearchSupplier, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 50, 400, 30));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/ijse/fms/images/Search.png"))); // NOI18N
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 50, 40, 30));

        tblItem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "BatchId", "ItemName", "Amount", "UnitPrice"
            }
        ));
        jScrollPane1.setViewportView(tblItem);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 100, 1230, 480));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setOpaque(true);
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1360, 610));
    }// </editor-fold>//GEN-END:initComponents

    private void txtSearchSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchSupplierActionPerformed

    }//GEN-LAST:event_txtSearchSupplierActionPerformed

    private void txtSearchSupplierKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchSupplierKeyReleased
        
    }//GEN-LAST:event_txtSearchSupplierKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblItem;
    private javax.swing.JTextField txtSearchSupplier;
    // End of variables declaration//GEN-END:variables

    private void viewAllItems() {
        try {
            ArrayList<ViewItemNameBatchDTO> itemNameList = viewItemNameBatchController.getAll();
            for (ViewItemNameBatchDTO itemNameList1 : itemNameList) {
                Object[] ob ={itemNameList1.getBatchId(),itemNameList1.getItemName(),itemNameList1.getAmount(),itemNameList1.getUnitPrice()};
                dtm.addRow(ob);
            }
        } catch (Exception ex) {
            Logger.getLogger(pnlViewAllItem.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
