/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.ijse.fms.view.panel;

import edu.ijse.fms.common.IDGenerator;
import edu.ijse.fms.controller.ControllerFactory;
import edu.ijse.fms.controller.custom.SupplierController;
import edu.ijse.fms.dto.SupplierDTO;
import edu.ijse.fms.view.AdminMainFrame;
import edu.ijse.fms.view.SearchDialog;
import java.awt.Color;

import java.awt.LayoutManager;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.naming.ldap.ControlFactory;
import javax.swing.ButtonModel;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import javax.swing.border.Border;
import javax.swing.border.LineBorder;

/**
 *
 * @author Gnanod
 */
public class SupplierPanel extends javax.swing.JPanel {

    private SupplierController supplierController;

    /**
     * Creates new form SupplierPanel
     */
    public SupplierPanel() {
        initComponents();
        supplierController = (SupplierController) ControllerFactory.getInstance().getController(ControllerFactory.ControllerTypes.SUPPLIER);
        //  btnEnabled(false);
        getID();
        //btnSupplierGroup.
    }

//    public SupplierPanel(LayoutManager layout) {
//        super(layout);
//
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSupplierGroup = new javax.swing.ButtonGroup();
        pnlManageSupplier = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        txtSupplierCompanyAddress = new javax.swing.JTextField();
        txtSupplierTelNumber = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        btnSupplierMale = new javax.swing.JRadioButton();
        btnSupplierFemale = new javax.swing.JRadioButton();
        txtSupplierAddress = new javax.swing.JTextField();
        txtSupplierCompanyName = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        btnSupplierDelete = new javax.swing.JLabel();
        btnSupplierUpdate = new javax.swing.JLabel();
        btnSupplierAdd = new javax.swing.JLabel();
        btnSupplierSearch = new javax.swing.JLabel();
        jXLabel1 = new org.jdesktop.swingx.JXLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtSupplierId = new javax.swing.JTextField();
        txtSupplierName = new javax.swing.JTextField();

        pnlManageSupplier.setBackground(new java.awt.Color(255, 255, 255));
        pnlManageSupplier.setToolTipText("");
        pnlManageSupplier.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel24.setBackground(new java.awt.Color(255, 255, 255));
        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(27, 157, 175));
        jLabel24.setText("          Supplier Name");
        jLabel24.setToolTipText("");
        jLabel24.setOpaque(true);
        jLabel24.setRequestFocusEnabled(false);
        pnlManageSupplier.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, 260, 40));

        jLabel28.setBackground(new java.awt.Color(255, 255, 255));
        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(27, 157, 175));
        jLabel28.setText("          Gender");
        jLabel28.setToolTipText("");
        jLabel28.setOpaque(true);
        jLabel28.setRequestFocusEnabled(false);
        pnlManageSupplier.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, 260, 40));

        jLabel30.setBackground(new java.awt.Color(255, 255, 255));
        jLabel30.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(27, 157, 175));
        jLabel30.setText("          Tel Number");
        jLabel30.setToolTipText("");
        jLabel30.setOpaque(true);
        jLabel30.setRequestFocusEnabled(false);
        pnlManageSupplier.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 220, 260, 40));

        jLabel31.setBackground(new java.awt.Color(255, 255, 255));
        jLabel31.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(27, 157, 175));
        jLabel31.setText("          Company Address");
        jLabel31.setToolTipText("");
        jLabel31.setOpaque(true);
        jLabel31.setRequestFocusEnabled(false);
        pnlManageSupplier.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 370, 260, 40));

        txtSupplierCompanyAddress.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtSupplierCompanyAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSupplierCompanyAddressActionPerformed(evt);
            }
        });
        txtSupplierCompanyAddress.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSupplierCompanyAddressKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSupplierCompanyAddressKeyReleased(evt);
            }
        });
        pnlManageSupplier.add(txtSupplierCompanyAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 370, 400, 40));

        txtSupplierTelNumber.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtSupplierTelNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSupplierTelNumberActionPerformed(evt);
            }
        });
        txtSupplierTelNumber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSupplierTelNumberKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSupplierTelNumberKeyReleased(evt);
            }
        });
        pnlManageSupplier.add(txtSupplierTelNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 220, 400, 40));

        jLabel32.setBackground(new java.awt.Color(255, 255, 255));
        jLabel32.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(27, 157, 175));
        jLabel32.setText("          Address");
        jLabel32.setToolTipText("");
        jLabel32.setOpaque(true);
        jLabel32.setRequestFocusEnabled(false);
        pnlManageSupplier.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 270, 260, 40));

        jLabel33.setBackground(new java.awt.Color(255, 255, 255));
        jLabel33.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(27, 157, 175));
        jLabel33.setText("          Company Name");
        jLabel33.setToolTipText("");
        jLabel33.setOpaque(true);
        jLabel33.setRequestFocusEnabled(false);
        pnlManageSupplier.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 320, 260, 40));

        btnSupplierMale.setBackground(new java.awt.Color(255, 255, 255));
        btnSupplierGroup.add(btnSupplierMale);
        btnSupplierMale.setSelected(true);
        btnSupplierMale.setText("Male");
        pnlManageSupplier.add(btnSupplierMale, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 180, 140, -1));

        btnSupplierFemale.setBackground(new java.awt.Color(255, 255, 255));
        btnSupplierGroup.add(btnSupplierFemale);
        btnSupplierFemale.setText("Female");
        pnlManageSupplier.add(btnSupplierFemale, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 180, 100, -1));

        txtSupplierAddress.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtSupplierAddress.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtSupplierAddressMouseClicked(evt);
            }
        });
        txtSupplierAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSupplierAddressActionPerformed(evt);
            }
        });
        txtSupplierAddress.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSupplierAddressKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSupplierAddressKeyReleased(evt);
            }
        });
        pnlManageSupplier.add(txtSupplierAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 270, 400, 40));

        txtSupplierCompanyName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtSupplierCompanyName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSupplierCompanyNameActionPerformed(evt);
            }
        });
        txtSupplierCompanyName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSupplierCompanyNameKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSupplierCompanyNameKeyReleased(evt);
            }
        });
        pnlManageSupplier.add(txtSupplierCompanyName, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 320, 400, 40));

        jLabel34.setBackground(new java.awt.Color(255, 255, 255));
        jLabel34.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(53, 126, 120));
        jLabel34.setText("                        Manage Supplier");
        jLabel34.setToolTipText("");
        jLabel34.setOpaque(true);
        pnlManageSupplier.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 0, 770, 50));

        btnSupplierDelete.setBackground(new java.awt.Color(255, 255, 255));
        btnSupplierDelete.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnSupplierDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/ijse/fms/images/Remove User Male_26px.png"))); // NOI18N
        btnSupplierDelete.setText("       Delete");
        btnSupplierDelete.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(27, 157, 175)));
        btnSupplierDelete.setOpaque(true);
        btnSupplierDelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSupplierDeleteMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSupplierDeleteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSupplierDeleteMouseExited(evt);
            }
        });
        pnlManageSupplier.add(btnSupplierDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 530, 140, 50));

        btnSupplierUpdate.setBackground(new java.awt.Color(255, 255, 255));
        btnSupplierUpdate.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnSupplierUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/ijse/fms/images/Change User Male_26px.png"))); // NOI18N
        btnSupplierUpdate.setText("      Update");
        btnSupplierUpdate.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(27, 157, 175)));
        btnSupplierUpdate.setOpaque(true);
        btnSupplierUpdate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSupplierUpdateMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSupplierUpdateMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSupplierUpdateMouseExited(evt);
            }
        });
        pnlManageSupplier.add(btnSupplierUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 530, 140, 50));

        btnSupplierAdd.setBackground(new java.awt.Color(255, 255, 255));
        btnSupplierAdd.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnSupplierAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/ijse/fms/images/Add User Male_26px.png"))); // NOI18N
        btnSupplierAdd.setText("       Add");
        btnSupplierAdd.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(27, 157, 175)));
        btnSupplierAdd.setOpaque(true);
        btnSupplierAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSupplierAddMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSupplierAddMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSupplierAddMouseExited(evt);
            }
        });
        pnlManageSupplier.add(btnSupplierAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 530, 140, 50));

        btnSupplierSearch.setBackground(new java.awt.Color(255, 255, 255));
        btnSupplierSearch.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnSupplierSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/ijse/fms/images/Find User Male_26px.png"))); // NOI18N
        btnSupplierSearch.setText("      Search");
        btnSupplierSearch.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(27, 157, 175)));
        btnSupplierSearch.setOpaque(true);
        btnSupplierSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSupplierSearchMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSupplierSearchMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSupplierSearchMouseExited(evt);
            }
        });
        pnlManageSupplier.add(btnSupplierSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 530, 140, 50));

        jXLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jXLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(40, 202, 204), 2));
        jXLabel1.setOpaque(true);
        pnlManageSupplier.add(jXLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 500, 820, 110));

        jLabel29.setBackground(new java.awt.Color(255, 255, 255));
        jLabel29.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(27, 157, 175));
        jLabel29.setText("          Supplier Id");
        jLabel29.setToolTipText("");
        jLabel29.setOpaque(true);
        jLabel29.setRequestFocusEnabled(false);
        pnlManageSupplier.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 260, 40));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("xxx-xxxxxxx");
        pnlManageSupplier.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 240, 100, -1));

        txtSupplierId.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtSupplierId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSupplierIdActionPerformed(evt);
            }
        });
        txtSupplierId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSupplierIdKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSupplierIdKeyReleased(evt);
            }
        });
        pnlManageSupplier.add(txtSupplierId, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 70, 400, 40));

        txtSupplierName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtSupplierName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSupplierNameActionPerformed(evt);
            }
        });
        txtSupplierName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSupplierNameKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSupplierNameKeyReleased(evt);
            }
        });
        pnlManageSupplier.add(txtSupplierName, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 120, 400, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlManageSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, 1070, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(pnlManageSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, 660, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtSupplierCompanyAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSupplierCompanyAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSupplierCompanyAddressActionPerformed

    private void txtSupplierTelNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSupplierTelNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSupplierTelNumberActionPerformed

    private void txtSupplierAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSupplierAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSupplierAddressActionPerformed

    private void txtSupplierCompanyNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSupplierCompanyNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSupplierCompanyNameActionPerformed

    private void btnSupplierAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSupplierAddMouseClicked

        String supplierName = txtSupplierName.getText();

        String supplierId = txtSupplierId.getText();
        String supplierGender = "Male";
        if (btnSupplierMale.isSelected()) {
            supplierGender = "Male";
        }
        if (btnSupplierFemale.isSelected()) {
            supplierGender = "Female";
        }
        String supplierTelNumber = txtSupplierTelNumber.getText();
        String supplierAddress = txtSupplierAddress.getText();
        String supplierCompanyName = txtSupplierCompanyName.getText();
        String supplierCompanyAddress = txtSupplierCompanyAddress.getText();
        SupplierDTO supplier = new SupplierDTO(supplierName, supplierId, supplierGender, supplierTelNumber, supplierAddress, supplierCompanyName, supplierCompanyAddress);
        if (supplierName.isEmpty()) {
            txtSupplierName.setBorder(new LineBorder(Color.red, 1));
        }
        if (supplierId.isEmpty()) {
            txtSupplierName.setBorder(new LineBorder(Color.red, 1));
        }
        
        if (supplierAddress.isEmpty()) {
            txtSupplierAddress.setBorder(new LineBorder(Color.red, 1));
        }
        if (supplierCompanyName.isEmpty()) {
            txtSupplierCompanyName.setBorder(new LineBorder(Color.red, 1));
        }
        if (supplierCompanyAddress.isEmpty()) {
            txtSupplierCompanyAddress.setBorder(new LineBorder(Color.red, 1));
        }
        if (supplierTelNumber.isEmpty()) {
            txtSupplierTelNumber.setBorder(new LineBorder(Color.red, 1));
            
        }
        if(supplierName.isEmpty() == false && supplierTelNumber.isEmpty()== false && supplierAddress.isEmpty() == false && supplierCompanyName.isEmpty() == false && supplierCompanyAddress.isEmpty() == false) {
            try {

                boolean isAdded = supplierController.add(supplier);
                if (isAdded) {
                    JOptionPane.showMessageDialog(this, "Added sucessfully");
                    getID();
                    textFieldNull();
                } else {
                    JOptionPane.showMessageDialog(this, "oops Added Fail", "Error", JOptionPane.ERROR_MESSAGE);

                }
            } catch (SQLException ex) {
                String errorMsg;
                switch (ex.getErrorCode()) {
                    case 1062:
                        errorMsg = "Duplicate entry has been found. Please enter valid Supplier Id to proceed.";
                        break;
                    default:
                        errorMsg = "Supplier has been failed to add";
                        break;
                }
                JOptionPane.showMessageDialog(this, errorMsg, "Error", JOptionPane.ERROR_MESSAGE);

            } catch (Exception ex) {
                Logger.getLogger(SupplierPanel.class.getName()).log(Level.SEVERE, null, ex);

            }
        }


    }//GEN-LAST:event_btnSupplierAddMouseClicked

    private void btnSupplierSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSupplierSearchMouseClicked
        SearchDialog supplier = new SearchDialog(null, true, this);
        supplier.setVisible(true);
    }//GEN-LAST:event_btnSupplierSearchMouseClicked

    private void btnSupplierDeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSupplierDeleteMouseClicked
        String id = txtSupplierId.getText();
        try {
            boolean isDeleted = supplierController.delete(id);
            if (isDeleted) {
                JOptionPane.showMessageDialog(this, "Supplier is deleted");
            } else {
                JOptionPane.showMessageDialog(this, "Deleted Fail");
            }
        } catch (Exception ex) {
            Logger.getLogger(SupplierPanel.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnSupplierDeleteMouseClicked

    private void btnSupplierUpdateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSupplierUpdateMouseClicked
        String supplierName = txtSupplierId.getText();
        String supplierId = txtSupplierId.getText();
        String supplierGender = "Male";
        if (btnSupplierMale.isSelected()) {
            supplierGender = "Male";

        }
        if (btnSupplierFemale.isSelected()) {
            supplierGender = "Female";
        }
        String supplierTelNumber = txtSupplierTelNumber.getText();
        String supplierAddress = txtSupplierAddress.getText();
        String supplierCompanyName = txtSupplierCompanyName.getText();
        String supplierCompanyAddress = txtSupplierCompanyAddress.getText();

        SupplierDTO supplier = new SupplierDTO(supplierName, supplierId, supplierGender, supplierTelNumber, supplierAddress, supplierCompanyName, supplierCompanyAddress);
        if (supplierName.isEmpty()) {
            txtSupplierName.setBorder(new LineBorder(Color.red, 1));
        }
        if (supplierId.isEmpty()) {
            txtSupplierName.setBorder(new LineBorder(Color.red, 1));
        }
        if (!(supplierTelNumber.matches("\\d{3}-\\d{7}"))) {
            txtSupplierTelNumber.setBorder(new LineBorder(Color.red, 1));
        }
        if (supplierAddress.isEmpty()) {
            txtSupplierAddress.setBorder(new LineBorder(Color.red, 1));
        }
        if (supplierCompanyName.isEmpty()) {
            txtSupplierCompanyName.setBorder(new LineBorder(Color.red, 1));
        }
        if (supplierCompanyAddress.isEmpty()) {
            txtSupplierCompanyAddress.setBorder(new LineBorder(Color.red, 1));
        }
        if(supplierName.isEmpty() == false && supplierTelNumber.matches("\\d{3}-\\d{7}") == false && supplierAddress.isEmpty() == false && supplierCompanyName.isEmpty() == false && supplierCompanyAddress.isEmpty() == false) {
        
        try {
            boolean isUpdated = supplierController.update(supplier);
            if (isUpdated) {
                JOptionPane.showMessageDialog(this, "Updated sucessfully");
            } else {
                JOptionPane.showMessageDialog(this, "Oops Updated Fail", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (SQLException ex) {
            String errorMsg;
            switch (ex.getErrorCode()) {
                case 1062:
                    errorMsg = "Duplicate entry has been found. Please enter valid Supplier Id to proceed.";
                    break;
                default:
                    errorMsg = "Supplier has been failed to add";
                    break;
            }
            JOptionPane.showMessageDialog(this, errorMsg, "Error", JOptionPane.ERROR_MESSAGE);
        } catch (Exception ex) {
            Logger.getLogger(SupplierPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
    }//GEN-LAST:event_btnSupplierUpdateMouseClicked

    private void txtSupplierTelNumberKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSupplierTelNumberKeyPressed
        switch (evt.getKeyCode()) {
            case KeyEvent.VK_ENTER:
                txtSupplierAddress.requestFocus();
                break;
            case KeyEvent.VK_DOWN:
                txtSupplierAddress.requestFocus();
                break;
            case KeyEvent.VK_UP:
                txtSupplierId.requestFocus();
                break;
        }
    }//GEN-LAST:event_txtSupplierTelNumberKeyPressed

    private void txtSupplierAddressMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSupplierAddressMouseClicked


    }//GEN-LAST:event_txtSupplierAddressMouseClicked

    private void txtSupplierAddressKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSupplierAddressKeyPressed
        switch (evt.getKeyCode()) {
            case KeyEvent.VK_ENTER:
                txtSupplierCompanyName.requestFocus();
                break;
            case KeyEvent.VK_DOWN:
                txtSupplierCompanyName.requestFocus();
                break;
            case KeyEvent.VK_UP:
                txtSupplierTelNumber.requestFocus();
                break;
        }
    }//GEN-LAST:event_txtSupplierAddressKeyPressed

    private void txtSupplierCompanyNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSupplierCompanyNameKeyPressed
        switch (evt.getKeyCode()) {
            case KeyEvent.VK_ENTER:
                txtSupplierCompanyAddress.requestFocus();
                break;
            case KeyEvent.VK_DOWN:
                txtSupplierCompanyAddress.requestFocus();
                break;
            case KeyEvent.VK_UP:
                txtSupplierAddress.requestFocus();
                break;
        }
    }//GEN-LAST:event_txtSupplierCompanyNameKeyPressed

    private void txtSupplierCompanyAddressKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSupplierCompanyAddressKeyPressed
        switch (evt.getKeyCode()) {
            case KeyEvent.VK_ENTER:
                txtSupplierId.requestFocus();
                break;
            case KeyEvent.VK_UP:
                txtSupplierCompanyName.requestFocus();
                break;
        }
    }//GEN-LAST:event_txtSupplierCompanyAddressKeyPressed

    private void txtSupplierTelNumberKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSupplierTelNumberKeyReleased
      String supplierTelNumber = txtSupplierTelNumber.getText();
      if(!supplierTelNumber.matches("\\d{3}-\\d{7}")){
          txtSupplierTelNumber.setBorder(new LineBorder(Color.red, 1));
      }else{
          txtSupplierTelNumber.setBorder(new LineBorder(Color.black, 1));
      }
    }//GEN-LAST:event_txtSupplierTelNumberKeyReleased

    private void txtSupplierAddressKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSupplierAddressKeyReleased
       String supplierAddress = txtSupplierAddress.getText();
      if(supplierAddress.isEmpty()){
          txtSupplierTelNumber.setBorder(new LineBorder(Color.red, 1));
      }else{
          txtSupplierTelNumber.setBorder(new LineBorder(Color.BLACK, 1));
      } 
    }//GEN-LAST:event_txtSupplierAddressKeyReleased

    private void txtSupplierCompanyNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSupplierCompanyNameKeyReleased
       String supplierCompanyName= txtSupplierCompanyName.getText();
      if(supplierCompanyName.isEmpty()){
          txtSupplierTelNumber.setBorder(new LineBorder(Color.red, 1));
      }else{
          txtSupplierTelNumber.setBorder(new LineBorder(Color.BLACK, 1));
      }  
    }//GEN-LAST:event_txtSupplierCompanyNameKeyReleased

    private void txtSupplierCompanyAddressKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSupplierCompanyAddressKeyReleased
       String supplierCompanyAddress= txtSupplierCompanyAddress.getText();
      if(supplierCompanyAddress.isEmpty()){
          txtSupplierTelNumber.setBorder(new LineBorder(Color.red, 1));
      }else{
          txtSupplierTelNumber.setBorder(new LineBorder(Color.BLACK, 1));
      } 
    }//GEN-LAST:event_txtSupplierCompanyAddressKeyReleased

    private void txtSupplierIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSupplierIdActionPerformed
      String supplierCompanyName= txtSupplierCompanyName.getText();
      if(supplierCompanyName.isEmpty()){
          txtSupplierTelNumber.setBorder(new LineBorder(Color.red, 1));
      }else{
          txtSupplierTelNumber.setBorder(new LineBorder(Color.BLACK, 1));
      } 
    }//GEN-LAST:event_txtSupplierIdActionPerformed

    private void txtSupplierIdKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSupplierIdKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSupplierIdKeyPressed

    private void txtSupplierIdKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSupplierIdKeyReleased
      String id = txtSupplierId.getText();
      if(id.isEmpty()){
          txtSupplierId.setBorder(new LineBorder(Color.red, 1));
      }else{
          txtSupplierId.setBorder(new LineBorder(Color.black, 1));
      }
    }//GEN-LAST:event_txtSupplierIdKeyReleased

    private void txtSupplierNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSupplierNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSupplierNameActionPerformed

    private void txtSupplierNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSupplierNameKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSupplierNameKeyPressed

    private void txtSupplierNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSupplierNameKeyReleased
        String name = txtSupplierName.getText();
      if(name.isEmpty()){
          txtSupplierName.setBorder(new LineBorder(Color.red, 1));
      }else{
          txtSupplierName.setBorder(new LineBorder(Color.black, 1));
      }
    }//GEN-LAST:event_txtSupplierNameKeyReleased

    private void btnSupplierAddMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSupplierAddMouseEntered
         btnSupplierAdd.setBackground(new Color(40, 202, 204));
    }//GEN-LAST:event_btnSupplierAddMouseEntered

    private void btnSupplierAddMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSupplierAddMouseExited
        btnSupplierAdd.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_btnSupplierAddMouseExited

    private void btnSupplierSearchMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSupplierSearchMouseEntered
        btnSupplierSearch.setBackground(new Color(40, 202, 204));
    }//GEN-LAST:event_btnSupplierSearchMouseEntered

    private void btnSupplierSearchMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSupplierSearchMouseExited
       btnSupplierSearch.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_btnSupplierSearchMouseExited

    private void btnSupplierUpdateMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSupplierUpdateMouseEntered
        btnSupplierUpdate.setBackground(new Color(40, 202, 204));
    }//GEN-LAST:event_btnSupplierUpdateMouseEntered

    private void btnSupplierUpdateMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSupplierUpdateMouseExited
        btnSupplierUpdate.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_btnSupplierUpdateMouseExited

    private void btnSupplierDeleteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSupplierDeleteMouseEntered
        btnSupplierDelete.setBackground(new Color(40, 202, 204));
    }//GEN-LAST:event_btnSupplierDeleteMouseEntered

    private void btnSupplierDeleteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSupplierDeleteMouseExited
        btnSupplierDelete.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_btnSupplierDeleteMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnSupplierAdd;
    private javax.swing.JLabel btnSupplierDelete;
    private javax.swing.JRadioButton btnSupplierFemale;
    private javax.swing.ButtonGroup btnSupplierGroup;
    private javax.swing.JRadioButton btnSupplierMale;
    private javax.swing.JLabel btnSupplierSearch;
    private javax.swing.JLabel btnSupplierUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private org.jdesktop.swingx.JXLabel jXLabel1;
    private javax.swing.JPanel pnlManageSupplier;
    private javax.swing.JTextField txtSupplierAddress;
    private javax.swing.JTextField txtSupplierCompanyAddress;
    private javax.swing.JTextField txtSupplierCompanyName;
    private javax.swing.JTextField txtSupplierId;
    private javax.swing.JTextField txtSupplierName;
    private javax.swing.JTextField txtSupplierTelNumber;
    // End of variables declaration//GEN-END:variables
//    public void doValidate() {
//        String tel = txtSupplierTelNumber.getText().toString();
//        if (!txtSupplierId.getText().isEmpty()) {
//           
//            if (!txtSupplierId.getText().isEmpty()) {
//                if (!(tel.matches("\\d{3}-\\d{7}"))) {
//
//                    if (!txtSupplierAddress.getText().isEmpty()) {
//                        if (!txtSupplierCompanyName.getText().isEmpty()) {
//                            if (!txtSupplierCompanyAddress.getText().isEmpty()) {
//                                btnEnabled(true);
//                            }
//                        }
//                    }
//                }
//            }
//        }
//    }

    public void doValidate() {
        String tel = txtSupplierTelNumber.getText().toString();
        if (txtSupplierName.getText().isEmpty()) {
            txtSupplierName.setBorder(new LineBorder(Color.red, 1));
            if (txtSupplierId.getText().isEmpty()) {
                txtSupplierName.setBorder(new LineBorder(Color.red, 1));
                if (!(tel.matches("\\d{3}-\\d{8}"))) {
                    txtSupplierTelNumber.setBorder(new LineBorder(Color.red, 1));
                    if (txtSupplierAddress.getText().isEmpty()) {
                        txtSupplierAddress.setBorder(new LineBorder(Color.red, 1));
                        if (!txtSupplierCompanyName.getText().isEmpty()) {
                            txtSupplierCompanyName.setBorder(new LineBorder(Color.red, 1));
                            if (!txtSupplierCompanyAddress.getText().isEmpty()) {
                                txtSupplierCompanyAddress.setBorder(new LineBorder(Color.red, 1));
                                //btnEnabled(true);
                            }
                        }
                    }
                }
            }
        }
//         if (supplierName.isEmpty()) {
//            txtSupplierName.setBorder(new LineBorder(Color.red, 1));
//            }
//        if (supplierId.isEmpty()) {
//                txtSupplierName.setBorder(new LineBorder(Color.red, 1));
//          }
//                if (!(supplierTelNumber.matches("\\d{3}-\\d{8}"))) {
//            
//                    txtSupplierTelNumber.setBorder(new LineBorder(Color.red, 1));
//     }
//                    if (supplierAddress.isEmpty()) {
//                        txtSupplierAddress.setBorder(new LineBorder(Color.red, 1));
//        }
//                        if (supplierCompanyName.isEmpty()) {
//                            txtSupplierCompanyName.setBorder(new LineBorder(Color.red, 1));
//}
//                            if (supplierCompanyAddress.isEmpty()) {
//                                txtSupplierCompanyAddress.setBorder(new LineBorder(Color.red, 1));
//}
        //btnEnabled(true);

    }

    public void btnEnabled(boolean enable, JComponent... cmp) {
        btnSupplierAdd.setEnabled(enable);
        btnSupplierDelete.setEnabled(enable);
        btnSupplierSearch.setEnabled(enable);
        btnSupplierUpdate.setEnabled(enable);
    }

    public void textFieldNull() {

        txtSupplierAddress.setText(null);
        txtSupplierName.setText(null);
        txtSupplierTelNumber.setText(null);
        txtSupplierCompanyAddress.setText(null);
        txtSupplierCompanyName.setText(null);

    }

    public void setSupplierDetails(SupplierDTO dto) {
        txtSupplierId.setText(dto.getSupplierId());
        txtSupplierName.setText(dto.getSupplierName());
        txtSupplierTelNumber.setText(dto.getSupplierTelNumber());
        String gender = dto.getSupplierGender();

        if (gender.equals("Male")) {

            btnSupplierMale.setSelected(true);

        } else {

            btnSupplierFemale.setSelected(true);

        }

        txtSupplierAddress.setText(dto.getSupplierAddress());
        txtSupplierCompanyName.setText(dto.getSupplierCompanyName());
        txtSupplierCompanyAddress.setText(dto.getSupplierCompanyAddress());

    }

    private void getID() {
        String newID;
        try {
            newID = IDGenerator.getNewID("supplier", "supplierId", "s");
            txtSupplierId.setText(newID);

        } catch (ClassNotFoundException | SQLException e) {
        }
    }

    
}
