/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.ijse.fms.view.panel;

import edu.ijse.fms.controller.ControllerFactory;
import edu.ijse.fms.controller.custom.BatchController;
import edu.ijse.fms.controller.custom.ViewItemNameBatchController;
import edu.ijse.fms.dto.ViewItemNameBatchDTO;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Gnanod
 */
public class ViewAllItemPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewAllItem
     */
    private BatchController batchController;
    private ViewItemNameBatchController viewItemNameBatchController;
    private DefaultTableModel dtm;

    public ViewAllItemPanel() {
        initComponents();

        viewItemNameBatchController = (ViewItemNameBatchController) ControllerFactory.getInstance().getController(ControllerFactory.ControllerTypes.ITEMNAMEBATCH);

        dtm = (DefaultTableModel) tblItem.getModel();
        viewAllItems();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel34 = new javax.swing.JLabel();
        txtSearchItem = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblItem = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1070, 660));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel34.setBackground(new java.awt.Color(255, 255, 255));
        jLabel34.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(53, 126, 120));
        jLabel34.setText("                                  View All Items");
        jLabel34.setToolTipText("");
        jLabel34.setOpaque(true);
        add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 0, 770, 50));

        txtSearchItem.setToolTipText("Type Item Name");
        txtSearchItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchItemActionPerformed(evt);
            }
        });
        txtSearchItem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchItemKeyReleased(evt);
            }
        });
        add(txtSearchItem, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 50, 400, 30));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/ijse/fms/images/Search.png"))); // NOI18N
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 50, 40, 30));

        tblItem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "BatchId", "ItemName", "Amount", "UnitPrice"
            }
        ));
        jScrollPane1.setViewportView(tblItem);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 100, 1230, 480));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setOpaque(true);
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1360, 610));
    }// </editor-fold>//GEN-END:initComponents

    private void txtSearchItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchItemActionPerformed

    }//GEN-LAST:event_txtSearchItemActionPerformed

    private void txtSearchItemKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchItemKeyReleased
            String type = txtSearchItem.getText();
            try{
                ArrayList<ViewItemNameBatchDTO> list = viewItemNameBatchController.searchAll(type);
                if(list == null){
                    JOptionPane.showMessageDialog(this,"Item Not Found");
                }else{
                    dtm.setRowCount(0);
                    for (ViewItemNameBatchDTO list1 : list) {
//                        tblItem.remo
                        Object [] ob = {list1.getBatchId(),list1.getItemName(),list1.getAmount(),list1.getUnitPrice()};
                        dtm.addRow(ob);
                    }
                }
                
            } catch (Exception ex) {
            Logger.getLogger(ViewAllItemPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_txtSearchItemKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblItem;
    private javax.swing.JTextField txtSearchItem;
    // End of variables declaration//GEN-END:variables
private void viewAllItems() {
        try {

            ArrayList<ViewItemNameBatchDTO> itemNameList = viewItemNameBatchController.getAll();
            //  System.out.println(itemNameList + "mmmmmmmmmmmmmmmmmmmmmm");
            if (itemNameList == null) {
                return;
            }
            for (ViewItemNameBatchDTO itemNameList1 : itemNameList) {
                Object[] ob = {itemNameList1.getBatchId(), itemNameList1.getItemName(), itemNameList1.getAmount(), itemNameList1.getUnitPrice()};
                
                dtm.addRow(ob);
            }
        } catch (Exception ex) {
            Logger.getLogger(pnlViewAllItem.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
private void loadPanel(){
    
}
}
