/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.ijse.fms.view;

import edu.ijse.fms.common.IDGenerator;
import edu.ijse.fms.controller.ControllerFactory;
import edu.ijse.fms.controller.custom.BrandController;
import edu.ijse.fms.controller.custom.ItemBrandNameController;
import edu.ijse.fms.controller.custom.ItemController;
import edu.ijse.fms.dto.BatchDTO;
import edu.ijse.fms.dto.BrandDTO;
import edu.ijse.fms.dto.ItemBrandNameDTO;
import edu.ijse.fms.dto.ItemDTO;
import edu.ijse.fms.view.panel.AddItemPanel;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Gnanod
 */
public class AddBatchFrame extends javax.swing.JDialog {

    /**
     * Creates new form AddBatchFrame
     */
    private BrandController brandController;
    private ItemController itemController;
    private ItemBrandNameController itemBrandNameController;

    public AddBatchFrame(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        brandController = (BrandController) ControllerFactory.getInstance().getController(ControllerFactory.ControllerTypes.BRAND);
        itemController = (ItemController) ControllerFactory.getInstance().getController(ControllerFactory.ControllerTypes.ITEM);
        itemBrandNameController = (ItemBrandNameController) ControllerFactory.getInstance().getController(ControllerFactory.ControllerTypes.ITEMBRANDNAME);
        getItemID();
        getBrandID();
        getBatchID();
        loadBrandNames();
        pnlVisible();
        setLocationRelativeTo(null);
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        txtBatchId = new javax.swing.JTextField();
        cmbBrand = new javax.swing.JComboBox();
        txtItemName = new javax.swing.JTextField();
        txtItemId = new javax.swing.JTextField();
        lblSaveBrand1 = new javax.swing.JLabel();
        btnAddNewBrand = new javax.swing.JLabel();
        AddBrandPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtBrandId = new javax.swing.JTextField();
        txtBrandName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel50.setBackground(new java.awt.Color(255, 255, 255));
        jLabel50.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel50.setForeground(new java.awt.Color(53, 126, 120));
        jLabel50.setText("                          Add New Item ");
        jLabel50.setToolTipText("");
        jLabel50.setOpaque(true);
        getContentPane().add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 0, 530, 50));

        jLabel51.setBackground(new java.awt.Color(255, 255, 255));
        jLabel51.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel51.setForeground(new java.awt.Color(27, 157, 175));
        jLabel51.setText("          Item  ID");
        jLabel51.setToolTipText("");
        jLabel51.setOpaque(true);
        jLabel51.setRequestFocusEnabled(false);
        getContentPane().add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 130, 30));

        jLabel56.setBackground(new java.awt.Color(255, 255, 255));
        jLabel56.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel56.setForeground(new java.awt.Color(27, 157, 175));
        jLabel56.setText("          Item Name");
        jLabel56.setToolTipText("");
        jLabel56.setOpaque(true);
        jLabel56.setRequestFocusEnabled(false);
        getContentPane().add(jLabel56, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 160, 30));

        jLabel59.setBackground(new java.awt.Color(255, 255, 255));
        jLabel59.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel59.setForeground(new java.awt.Color(27, 157, 175));
        jLabel59.setText("          Brand");
        jLabel59.setToolTipText("");
        jLabel59.setOpaque(true);
        jLabel59.setRequestFocusEnabled(false);
        getContentPane().add(jLabel59, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 160, 30));

        jLabel58.setBackground(new java.awt.Color(255, 255, 255));
        jLabel58.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel58.setForeground(new java.awt.Color(27, 157, 175));
        jLabel58.setText("          BatchId");
        jLabel58.setToolTipText("");
        jLabel58.setOpaque(true);
        jLabel58.setRequestFocusEnabled(false);
        getContentPane().add(jLabel58, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 160, 30));
        getContentPane().add(txtBatchId, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 190, 240, 30));

        cmbBrand.setEditable(true);
        cmbBrand.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        cmbBrand.setOpaque(false);
        cmbBrand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbBrandActionPerformed(evt);
            }
        });
        getContentPane().add(cmbBrand, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, 240, 30));
        getContentPane().add(txtItemName, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 110, 240, 30));

        txtItemId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtItemIdActionPerformed(evt);
            }
        });
        getContentPane().add(txtItemId, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 70, 240, 30));

        lblSaveBrand1.setBackground(new java.awt.Color(255, 255, 255));
        lblSaveBrand1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblSaveBrand1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/ijse/fms/images/Add Item save.png"))); // NOI18N
        lblSaveBrand1.setText("    Add");
        lblSaveBrand1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(27, 157, 175)));
        lblSaveBrand1.setOpaque(true);
        lblSaveBrand1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSaveBrand1MouseClicked(evt);
            }
        });
        getContentPane().add(lblSaveBrand1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 250, 120, 50));

        btnAddNewBrand.setBackground(new java.awt.Color(255, 255, 255));
        btnAddNewBrand.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnAddNewBrand.setText("      Add New Brand");
        btnAddNewBrand.setToolTipText("");
        btnAddNewBrand.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(40, 202, 204)));
        btnAddNewBrand.setOpaque(true);
        btnAddNewBrand.setRequestFocusEnabled(false);
        btnAddNewBrand.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddNewBrandMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAddNewBrandMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAddNewBrandMouseExited(evt);
            }
        });
        getContentPane().add(btnAddNewBrand, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 150, 200, 30));

        AddBrandPanel.setLayout(null);

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Add Brand");
        jLabel3.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(27, 157, 175)));
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel3.setOpaque(true);
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        AddBrandPanel.add(jLabel3);
        jLabel3.setBounds(160, 150, 120, 30);
        AddBrandPanel.add(txtBrandId);
        txtBrandId.setBounds(130, 60, 150, 30);
        AddBrandPanel.add(txtBrandName);
        txtBrandName.setBounds(130, 100, 150, 30);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(27, 157, 175));
        jLabel2.setText("Brand Name");
        jLabel2.setOpaque(true);
        AddBrandPanel.add(jLabel2);
        jLabel2.setBounds(40, 100, 90, 30);

        jLabel52.setBackground(new java.awt.Color(255, 255, 255));
        jLabel52.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel52.setForeground(new java.awt.Color(53, 126, 120));
        jLabel52.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel52.setText("               Add New Brand");
        jLabel52.setToolTipText("");
        jLabel52.setOpaque(true);
        AddBrandPanel.add(jLabel52);
        jLabel52.setBounds(60, 10, 170, 30);

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(27, 157, 175));
        jLabel4.setText("  Brand Id");
        jLabel4.setOpaque(true);
        AddBrandPanel.add(jLabel4);
        jLabel4.setBounds(30, 60, 90, 30);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(40, 202, 204)));
        jLabel1.setOpaque(true);
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel1MouseExited(evt);
            }
        });
        AddBrandPanel.add(jLabel1);
        jLabel1.setBounds(0, 0, 290, 190);

        getContentPane().add(AddBrandPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 190, 290, 190));

        jLabel48.setBackground(new java.awt.Color(255, 255, 255));
        jLabel48.setOpaque(true);
        getContentPane().add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, 390));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbBrandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbBrandActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbBrandActionPerformed

    private void txtItemIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtItemIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtItemIdActionPerformed

    private void lblSaveBrand1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSaveBrand1MouseClicked
        String itemId = txtItemId.getText();
        String itemName = txtItemName.getText();
        String name = (String) cmbBrand.getSelectedItem();
        String batchId = txtBatchId.getText(); //

        String brandId = null;
        try {
            brandId = brandController.getItemCode(name);
        } catch (Exception ex) {
            Logger.getLogger(AddItemPanel.class.getName()).log(Level.SEVERE, null, ex);
        }

        ItemDTO itemDto = new ItemDTO(itemId, itemName, brandId);

        String grnId = null;
        double unitPrice = 0;
        double amount = 0;
        BatchDTO batchDto = new BatchDTO();  //
        batchDto.setBatchId(batchId);         //
        batchDto.setItemId(itemId);            //

        batchDto.setGrnId(grnId);
        batchDto.setAmmount(amount);
        batchDto.setUnitPrice(unitPrice);
        try {
            boolean isAdded = itemController.add(itemDto, batchDto);
            System.out.println(isAdded);
            //boolean isAdded = itemController.add(itemDto);
            if (isAdded) {
                JOptionPane.showMessageDialog(this, "Added Sucessfully");
                getItemID();
            } else {
                JOptionPane.showMessageDialog(this, "Oops Added Fail", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (SQLException ex) {

            String errorMsg;
            switch (ex.getErrorCode()) {
                case 1062:
                    errorMsg = "Duplicate entry has been found. Please enter valid Item Id to proceed.";
                    break;
                default:
                    errorMsg = "Item has been failed to add";
                    break;
            }
            JOptionPane.showMessageDialog(this, errorMsg, "Error", JOptionPane.ERROR_MESSAGE);

        } catch (Exception ex) {
            Logger.getLogger(AddItemPanel.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_lblSaveBrand1MouseClicked

    private void btnAddNewBrandMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddNewBrandMouseClicked
        getBrandID();
        AddBrandPanel.setVisible(true);
    }//GEN-LAST:event_btnAddNewBrandMouseClicked

    private void btnAddNewBrandMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddNewBrandMouseEntered

    }//GEN-LAST:event_btnAddNewBrandMouseEntered

    private void btnAddNewBrandMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddNewBrandMouseExited

    }//GEN-LAST:event_btnAddNewBrandMouseExited

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        pnlVisible();
        String brandId = txtBrandId.getText();
        String brandName = txtBrandName.getText();
        BrandDTO brandDto = new BrandDTO(brandId, brandName);
        try {
            boolean isAdd = brandController.add(brandDto);

            if (isAdd) {
                JOptionPane.showMessageDialog(this, "Brand is added");
                loadBrandNames();
                getBrandID();
            } else {
                JOptionPane.showMessageDialog(this, "Oops Added Fail", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (SQLException ex) {
            String errorMsg;
            switch (ex.getErrorCode()) {
                case 1062:
                    errorMsg = "Duplicate entry has been found. Please enter valid Brand Id to proceed.";
                    break;
                default:
                    errorMsg = "Brand has been failed to add";
                    break;
            }
            JOptionPane.showMessageDialog(this, errorMsg, "Error", JOptionPane.ERROR_MESSAGE);

        } catch (Exception ex) {
            Logger.getLogger(AddItemPanel.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseExited

    }//GEN-LAST:event_jLabel1MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddBatchFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddBatchFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddBatchFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddBatchFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AddBatchFrame dialog = new AddBatchFrame(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AddBrandPanel;
    private javax.swing.JLabel btnAddNewBrand;
    private javax.swing.JComboBox cmbBrand;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel lblSaveBrand1;
    private javax.swing.JTextField txtBatchId;
    private javax.swing.JTextField txtBrandId;
    private javax.swing.JTextField txtBrandName;
    private javax.swing.JTextField txtItemId;
    private javax.swing.JTextField txtItemName;
    // End of variables declaration//GEN-END:variables


    public void pnlVisible() {
        AddBrandPanel.setVisible(false);
    }
    private void getBrandID() {
        String newID;
        try {
            newID = IDGenerator.getNewID("brand", "brandId", "B");
            txtBrandId.setText(newID);

        } catch (ClassNotFoundException | SQLException e) {
        }
    }

    private void getItemID() {
        String newID;
        try {
            newID = IDGenerator.getNewID("item", "itemId", "I");
            txtItemId.setText(newID);

        } catch (ClassNotFoundException | SQLException e) {
        }
    }
     private void getBatchID() {
        String newID;
        try {
            newID = IDGenerator.getNewID("Batch", "batchId", "B");
            txtBatchId.setText(newID);

        } catch (ClassNotFoundException | SQLException e) {
        }
    }
      private void loadBrandNames() {
        try {
            cmbBrand.removeAllItems();
            ArrayList<BrandDTO> brandList = brandController.getAll();
            System.out.println("Length " + brandList.size());
            for (BrandDTO brandDto : brandList) {
                cmbBrand.addItem(brandDto.getBrandName());
//                int itemCount = cmbBrand.getItemCount();
//                for (int i = 0; i < itemCount; i++) {
////                    String toString = cmbBrand.getItemAt(i).toString();
////                    if (!toString.equals(brandDto.getBrandName())) {
////                        cmbBrand.addItem(brandDto.getBrandName());
////                    }else{
////                         cmbBrand.addItem(brandDto.getBrandName());
////                    }
//                    System.out.println(brandDto.getBrandName());
//                     
//                }

            }
        } catch (Exception ex) {
            Logger.getLogger(AddItemPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
