/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.ijse.fms.view;

import edu.ijse.fms.common.IDGenerator;
import edu.ijse.fms.controller.ControllerFactory;
import edu.ijse.fms.controller.custom.SupplierController;
import edu.ijse.fms.dto.SupplierDTO;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.border.LineBorder;
import static sun.rmi.registry.RegistryImpl.getID;

/**
 *
 * @author Gnanod
 */
public class AddSupplierFrame extends javax.swing.JDialog {
     private SupplierController supplierController;

    /**
     * Creates new form AddSupplierFrame
     */
    public AddSupplierFrame(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        supplierController = (SupplierController) ControllerFactory.getInstance().getController(ControllerFactory.ControllerTypes.SUPPLIER);
        getID();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtSupplierName = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        txtSupplierId = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        btnSupplierMale = new javax.swing.JRadioButton();
        btnSupplierFemale = new javax.swing.JRadioButton();
        btnSupplierAdd = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtSupplierAddress = new javax.swing.JTextField();
        txtSupplierCompanyName = new javax.swing.JTextField();
        txtSupplierCompanyAddress = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        txtSupplierTelNumber = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtSupplierName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtSupplierName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSupplierNameActionPerformed(evt);
            }
        });
        txtSupplierName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSupplierNameKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSupplierNameKeyReleased(evt);
            }
        });
        jPanel1.add(txtSupplierName, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 120, 400, 40));

        jLabel34.setBackground(new java.awt.Color(255, 255, 255));
        jLabel34.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(53, 126, 120));
        jLabel34.setText("                        Manage Supplier");
        jLabel34.setToolTipText("");
        jLabel34.setOpaque(true);
        jPanel1.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, 380, 50));

        jLabel29.setBackground(new java.awt.Color(255, 255, 255));
        jLabel29.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(27, 157, 175));
        jLabel29.setText("          Supplier Id");
        jLabel29.setToolTipText("");
        jLabel29.setOpaque(true);
        jLabel29.setRequestFocusEnabled(false);
        jPanel1.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 210, 40));

        txtSupplierId.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtSupplierId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSupplierIdActionPerformed(evt);
            }
        });
        txtSupplierId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSupplierIdKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSupplierIdKeyReleased(evt);
            }
        });
        jPanel1.add(txtSupplierId, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 70, 400, 40));

        jLabel24.setBackground(new java.awt.Color(255, 255, 255));
        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(27, 157, 175));
        jLabel24.setText("          Supplier Name");
        jLabel24.setToolTipText("");
        jLabel24.setOpaque(true);
        jLabel24.setRequestFocusEnabled(false);
        jPanel1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 210, 40));

        jLabel28.setBackground(new java.awt.Color(255, 255, 255));
        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(27, 157, 175));
        jLabel28.setText("          Gender");
        jLabel28.setToolTipText("");
        jLabel28.setOpaque(true);
        jLabel28.setRequestFocusEnabled(false);
        jPanel1.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 210, 40));

        btnSupplierMale.setBackground(new java.awt.Color(255, 255, 255));
        btnSupplierMale.setSelected(true);
        btnSupplierMale.setText("Male");
        jPanel1.add(btnSupplierMale, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 180, 140, -1));

        btnSupplierFemale.setBackground(new java.awt.Color(255, 255, 255));
        btnSupplierFemale.setText("Female");
        jPanel1.add(btnSupplierFemale, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 180, 100, -1));

        btnSupplierAdd.setBackground(new java.awt.Color(255, 255, 255));
        btnSupplierAdd.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnSupplierAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/ijse/fms/images/Add User Male_26px.png"))); // NOI18N
        btnSupplierAdd.setText("       Add");
        btnSupplierAdd.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(27, 157, 175)));
        btnSupplierAdd.setOpaque(true);
        btnSupplierAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSupplierAddMouseClicked(evt);
            }
        });
        jPanel1.add(btnSupplierAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 430, 140, 50));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("xxx-xxxxxxx");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 240, 100, -1));

        txtSupplierAddress.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtSupplierAddress.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtSupplierAddressMouseClicked(evt);
            }
        });
        txtSupplierAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSupplierAddressActionPerformed(evt);
            }
        });
        txtSupplierAddress.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSupplierAddressKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSupplierAddressKeyReleased(evt);
            }
        });
        jPanel1.add(txtSupplierAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 270, 400, 40));

        txtSupplierCompanyName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtSupplierCompanyName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSupplierCompanyNameActionPerformed(evt);
            }
        });
        txtSupplierCompanyName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSupplierCompanyNameKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSupplierCompanyNameKeyReleased(evt);
            }
        });
        jPanel1.add(txtSupplierCompanyName, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 320, 400, 40));

        txtSupplierCompanyAddress.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtSupplierCompanyAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSupplierCompanyAddressActionPerformed(evt);
            }
        });
        txtSupplierCompanyAddress.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSupplierCompanyAddressKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSupplierCompanyAddressKeyReleased(evt);
            }
        });
        jPanel1.add(txtSupplierCompanyAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 370, 400, 40));

        jLabel31.setBackground(new java.awt.Color(255, 255, 255));
        jLabel31.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(27, 157, 175));
        jLabel31.setText("          Company Address");
        jLabel31.setToolTipText("");
        jLabel31.setOpaque(true);
        jLabel31.setRequestFocusEnabled(false);
        jPanel1.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 220, 40));

        jLabel33.setBackground(new java.awt.Color(255, 255, 255));
        jLabel33.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(27, 157, 175));
        jLabel33.setText("          Company Name");
        jLabel33.setToolTipText("");
        jLabel33.setOpaque(true);
        jLabel33.setRequestFocusEnabled(false);
        jPanel1.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 210, 40));

        jLabel32.setBackground(new java.awt.Color(255, 255, 255));
        jLabel32.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(27, 157, 175));
        jLabel32.setText("          Address");
        jLabel32.setToolTipText("");
        jLabel32.setOpaque(true);
        jLabel32.setRequestFocusEnabled(false);
        jPanel1.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 210, 40));

        jLabel30.setBackground(new java.awt.Color(255, 255, 255));
        jLabel30.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(27, 157, 175));
        jLabel30.setText("          Tel Number");
        jLabel30.setToolTipText("");
        jLabel30.setOpaque(true);
        jLabel30.setRequestFocusEnabled(false);
        jPanel1.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 210, 40));

        txtSupplierTelNumber.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtSupplierTelNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSupplierTelNumberActionPerformed(evt);
            }
        });
        txtSupplierTelNumber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSupplierTelNumberKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSupplierTelNumberKeyReleased(evt);
            }
        });
        jPanel1.add(txtSupplierTelNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 220, 400, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, 490));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtSupplierNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSupplierNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSupplierNameActionPerformed

    private void txtSupplierNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSupplierNameKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSupplierNameKeyPressed

    private void txtSupplierNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSupplierNameKeyReleased
        String name = txtSupplierName.getText();
        if(name.isEmpty()){
            txtSupplierName.setBorder(new LineBorder(Color.red, 1));
        }else{
            txtSupplierName.setBorder(new LineBorder(Color.black, 1));
        }
    }//GEN-LAST:event_txtSupplierNameKeyReleased

    private void txtSupplierIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSupplierIdActionPerformed
        String supplierCompanyName= txtSupplierCompanyName.getText();
        if(supplierCompanyName.isEmpty()){
            txtSupplierTelNumber.setBorder(new LineBorder(Color.red, 1));
        }else{
            txtSupplierTelNumber.setBorder(new LineBorder(Color.BLACK, 1));
        }
    }//GEN-LAST:event_txtSupplierIdActionPerformed

    private void txtSupplierIdKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSupplierIdKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSupplierIdKeyPressed

    private void txtSupplierIdKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSupplierIdKeyReleased
        String id = txtSupplierId.getText();
        if(id.isEmpty()){
            txtSupplierId.setBorder(new LineBorder(Color.red, 1));
        }else{
            txtSupplierId.setBorder(new LineBorder(Color.black, 1));
        }
    }//GEN-LAST:event_txtSupplierIdKeyReleased

    private void txtSupplierTelNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSupplierTelNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSupplierTelNumberActionPerformed

    private void txtSupplierTelNumberKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSupplierTelNumberKeyPressed
        switch (evt.getKeyCode()) {
            case KeyEvent.VK_ENTER:
            txtSupplierAddress.requestFocus();
            break;
            case KeyEvent.VK_DOWN:
            txtSupplierAddress.requestFocus();
            break;
            case KeyEvent.VK_UP:
            txtSupplierId.requestFocus();
            break;
        }
    }//GEN-LAST:event_txtSupplierTelNumberKeyPressed

    private void txtSupplierTelNumberKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSupplierTelNumberKeyReleased
        String supplierTelNumber = txtSupplierTelNumber.getText();
        if(!supplierTelNumber.matches("\\d{3}-\\d{7}")){
            txtSupplierTelNumber.setBorder(new LineBorder(Color.red, 1));
        }else{
            txtSupplierTelNumber.setBorder(new LineBorder(Color.black, 1));
        }
    }//GEN-LAST:event_txtSupplierTelNumberKeyReleased

    private void txtSupplierCompanyAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSupplierCompanyAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSupplierCompanyAddressActionPerformed

    private void txtSupplierCompanyAddressKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSupplierCompanyAddressKeyPressed
        switch (evt.getKeyCode()) {
            case KeyEvent.VK_ENTER:
            txtSupplierId.requestFocus();
            break;
            case KeyEvent.VK_UP:
            txtSupplierCompanyName.requestFocus();
            break;
        }
    }//GEN-LAST:event_txtSupplierCompanyAddressKeyPressed

    private void txtSupplierCompanyAddressKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSupplierCompanyAddressKeyReleased
        String supplierCompanyAddress= txtSupplierCompanyAddress.getText();
        if(supplierCompanyAddress.isEmpty()){
            txtSupplierTelNumber.setBorder(new LineBorder(Color.red, 1));
        }else{
            txtSupplierTelNumber.setBorder(new LineBorder(Color.BLACK, 1));
        }
    }//GEN-LAST:event_txtSupplierCompanyAddressKeyReleased

    private void txtSupplierCompanyNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSupplierCompanyNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSupplierCompanyNameActionPerformed

    private void txtSupplierCompanyNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSupplierCompanyNameKeyPressed
        switch (evt.getKeyCode()) {
            case KeyEvent.VK_ENTER:
            txtSupplierCompanyAddress.requestFocus();
            break;
            case KeyEvent.VK_DOWN:
            txtSupplierCompanyAddress.requestFocus();
            break;
            case KeyEvent.VK_UP:
            txtSupplierAddress.requestFocus();
            break;
        }
    }//GEN-LAST:event_txtSupplierCompanyNameKeyPressed

    private void txtSupplierCompanyNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSupplierCompanyNameKeyReleased
        String supplierCompanyName= txtSupplierCompanyName.getText();
        if(supplierCompanyName.isEmpty()){
            txtSupplierTelNumber.setBorder(new LineBorder(Color.red, 1));
        }else{
            txtSupplierTelNumber.setBorder(new LineBorder(Color.BLACK, 1));
        }
    }//GEN-LAST:event_txtSupplierCompanyNameKeyReleased

    private void txtSupplierAddressMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSupplierAddressMouseClicked

    }//GEN-LAST:event_txtSupplierAddressMouseClicked

    private void txtSupplierAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSupplierAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSupplierAddressActionPerformed

    private void txtSupplierAddressKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSupplierAddressKeyPressed
        switch (evt.getKeyCode()) {
            case KeyEvent.VK_ENTER:
            txtSupplierCompanyName.requestFocus();
            break;
            case KeyEvent.VK_DOWN:
            txtSupplierCompanyName.requestFocus();
            break;
            case KeyEvent.VK_UP:
            txtSupplierTelNumber.requestFocus();
            break;
        }
    }//GEN-LAST:event_txtSupplierAddressKeyPressed

    private void txtSupplierAddressKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSupplierAddressKeyReleased
        String supplierAddress = txtSupplierAddress.getText();
        if(supplierAddress.isEmpty()){
            txtSupplierTelNumber.setBorder(new LineBorder(Color.red, 1));
        }else{
            txtSupplierTelNumber.setBorder(new LineBorder(Color.BLACK, 1));
        }
    }//GEN-LAST:event_txtSupplierAddressKeyReleased

    private void btnSupplierAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSupplierAddMouseClicked

        String supplierName = txtSupplierName.getText();

        String supplierId = txtSupplierId.getText();
        String supplierGender = "Male";
        if (btnSupplierMale.isSelected()) {
            supplierGender = "Male";
        }
        if (btnSupplierFemale.isSelected()) {
            supplierGender = "Female";
        }
        String supplierTelNumber = txtSupplierTelNumber.getText();
        String supplierAddress = txtSupplierAddress.getText();
        String supplierCompanyName = txtSupplierCompanyName.getText();
        String supplierCompanyAddress = txtSupplierCompanyAddress.getText();
        SupplierDTO supplier = new SupplierDTO(supplierName, supplierId, supplierGender, supplierTelNumber, supplierAddress, supplierCompanyName, supplierCompanyAddress);
        if (supplierName.isEmpty()) {
            txtSupplierName.setBorder(new LineBorder(Color.red, 1));
        }
        if (supplierId.isEmpty()) {
            txtSupplierName.setBorder(new LineBorder(Color.red, 1));
        }

        if (supplierAddress.isEmpty()) {
            txtSupplierAddress.setBorder(new LineBorder(Color.red, 1));
        }
        if (supplierCompanyName.isEmpty()) {
            txtSupplierCompanyName.setBorder(new LineBorder(Color.red, 1));
        }
        if (supplierCompanyAddress.isEmpty()) {
            txtSupplierCompanyAddress.setBorder(new LineBorder(Color.red, 1));
        }
        if (supplierTelNumber.isEmpty()) {
            txtSupplierTelNumber.setBorder(new LineBorder(Color.red, 1));

        }
        if(supplierName.isEmpty() == false && supplierTelNumber.isEmpty()== false && supplierAddress.isEmpty() == false && supplierCompanyName.isEmpty() == false && supplierCompanyAddress.isEmpty() == false) {
            try {

                boolean isAdded = supplierController.add(supplier);
                if (isAdded) {
                    JOptionPane.showMessageDialog(this, "Added sucessfully");
                    getID();
                    textFieldNull();
                } else {
                    JOptionPane.showMessageDialog(this, "oops Added Fail", "Error", JOptionPane.ERROR_MESSAGE);

                }
            }catch(SQLException ex){
                String errorMsg;
                switch (ex.getErrorCode()) {
                    case 1062:
                    errorMsg = "Duplicate entry has been found. Please enter valid Supplier Id to proceed.";
                    break;
                    default:
                    errorMsg = "Supplier has been failed to add";
                    break;
                }
                JOptionPane.showMessageDialog(this, errorMsg, "Error", JOptionPane.ERROR_MESSAGE);

            } catch (Exception ex) {
                Logger.getLogger(AddSupplierFrame.class.getName()).log(Level.SEVERE, null, ex);
            } 
        }

    }//GEN-LAST:event_btnSupplierAddMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddSupplierFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddSupplierFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddSupplierFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddSupplierFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AddSupplierFrame dialog = new AddSupplierFrame(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnSupplierAdd;
    private javax.swing.JRadioButton btnSupplierFemale;
    private javax.swing.JRadioButton btnSupplierMale;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtSupplierAddress;
    private javax.swing.JTextField txtSupplierCompanyAddress;
    private javax.swing.JTextField txtSupplierCompanyName;
    private javax.swing.JTextField txtSupplierId;
    private javax.swing.JTextField txtSupplierName;
    private javax.swing.JTextField txtSupplierTelNumber;
    // End of variables declaration//GEN-END:variables

    private void textFieldNull() {
     txtSupplierAddress.setText(null);
        txtSupplierName.setText(null);
        txtSupplierTelNumber.setText(null);
        txtSupplierCompanyAddress.setText(null);
        txtSupplierCompanyName.setText(null);
    }
    private void getID() {
        String newID;
        try {
            newID = IDGenerator.getNewID("supplier", "supplierId", "s");
            txtSupplierId.setText(newID);

        } catch (ClassNotFoundException | SQLException e) {
        }
    }
    
    }
