/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.ijse.fms.view;

import com.sun.org.apache.xerces.internal.xs.ItemPSVI;
import edu.ijse.fms.db.ConnectionFactory;
import edu.ijse.fms.view.panel.AddItemPanel;
import edu.ijse.fms.view.panel.CustomerPanel;
import edu.ijse.fms.view.panel.ReportsPanel;
import edu.ijse.fms.view.panel.SupplierOrderPanel;
//import edu.ijse.fms.models.Item;
import edu.ijse.fms.view.panel.SupplierPanel;
import edu.ijse.fms.view.panel.UserPanel;
import java.awt.Color;
import java.awt.HeadlessException;
import java.awt.KeyEventPostProcessor;
import java.awt.KeyboardFocusManager;
import java.awt.event.KeyEvent;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Gnanod
 */
public class AdminMainFrame extends javax.swing.JFrame {
private static String userID;
    SupplierPanel supplierPanel;
    UserPanel userPanel;
    CustomerPanel customerPanel;
    AddItemPanel addItemPanel;
    SupplierOrderPanel supplierOrderPanel;

    /**
     * Creates new form MainFrame
     */
    
    public AdminMainFrame() {
    }

    public AdminMainFrame(String getType) {
        initComponents();
        userID=getType;
        if (userID.equals("Administrator")) {
            //JOptionPane.showMessageDialog(this, "ADMIN");
        }
        loadKeyListener();
        time();
        date();
        
        // System.out.println(ConnectionFactory.getInstance());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblMinimize = new javax.swing.JLabel();
        lblClose1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblClose = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblSupplierOrder = new javax.swing.JLabel();
        lblViewReports = new javax.swing.JLabel();
        lblManageUser = new javax.swing.JLabel();
        lblManageSupplier = new javax.swing.JLabel();
        lblManageCustomer = new javax.swing.JLabel();
        lblAddItem = new javax.swing.JLabel();
        lblGrn = new javax.swing.JLabel();
        lblLogOut = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblDate = new javax.swing.JLabel();
        lblTime = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        pnlItem = new javax.swing.JPanel();
        pnlReport = new javax.swing.JPanel();
        MainPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblMinimize.setBackground(new java.awt.Color(40, 202, 204));
        lblMinimize.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblMinimize.setText("  -");
        lblMinimize.setOpaque(true);
        lblMinimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMinimizeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblMinimizeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblMinimizeMouseExited(evt);
            }
        });
        jPanel1.add(lblMinimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(1290, 0, 40, 40));

        lblClose1.setBackground(new java.awt.Color(40, 202, 204));
        lblClose1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblClose1.setText("   X");
        lblClose1.setOpaque(true);
        lblClose1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblClose1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblClose1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblClose1MouseExited(evt);
            }
        });
        jPanel1.add(lblClose1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1330, 0, 40, 40));

        jLabel3.setBackground(new java.awt.Color(40, 202, 204));
        jLabel3.setOpaque(true);
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 40));

        lblClose.setBackground(new java.awt.Color(40, 202, 204));
        lblClose.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblClose.setText("   X");
        lblClose.setOpaque(true);
        lblClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCloseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblCloseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblCloseMouseExited(evt);
            }
        });
        jPanel1.add(lblClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(1330, 0, 40, 40));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblSupplierOrder.setBackground(new java.awt.Color(31, 40, 45));
        lblSupplierOrder.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblSupplierOrder.setForeground(new java.awt.Color(255, 255, 255));
        lblSupplierOrder.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblSupplierOrder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/ijse/fms/images/suppOrder.png"))); // NOI18N
        lblSupplierOrder.setText(" [F6]      Supplier Order");
        lblSupplierOrder.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        lblSupplierOrder.setOpaque(true);
        lblSupplierOrder.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSupplierOrderMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblSupplierOrderMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblSupplierOrderMouseExited(evt);
            }
        });
        jPanel2.add(lblSupplierOrder, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 300, 60));

        lblViewReports.setBackground(new java.awt.Color(31, 40, 45));
        lblViewReports.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblViewReports.setForeground(new java.awt.Color(255, 255, 255));
        lblViewReports.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblViewReports.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/ijse/fms/images/report.png"))); // NOI18N
        lblViewReports.setText(" [F7]      View Reports");
        lblViewReports.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        lblViewReports.setOpaque(true);
        lblViewReports.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblViewReportsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblViewReportsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblViewReportsMouseExited(evt);
            }
        });
        jPanel2.add(lblViewReports, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 300, 60));

        lblManageUser.setBackground(new java.awt.Color(31, 40, 45));
        lblManageUser.setDisplayedMnemonic('M');
        lblManageUser.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblManageUser.setForeground(new java.awt.Color(255, 255, 255));
        lblManageUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/ijse/fms/images/user.png"))); // NOI18N
        lblManageUser.setLabelFor(this);
        lblManageUser.setText(" [F1]      Manage User ");
        lblManageUser.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        lblManageUser.setOpaque(true);
        lblManageUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblManageUserMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblManageUserMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblManageUserMouseExited(evt);
            }
        });
        jPanel2.add(lblManageUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 60));

        lblManageSupplier.setBackground(new java.awt.Color(31, 40, 45));
        lblManageSupplier.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblManageSupplier.setForeground(new java.awt.Color(255, 255, 255));
        lblManageSupplier.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblManageSupplier.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/ijse/fms/images/User Group.png"))); // NOI18N
        lblManageSupplier.setText(" [F3]      Manage Supplier");
        lblManageSupplier.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        lblManageSupplier.setOpaque(true);
        lblManageSupplier.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblManageSupplierMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblManageSupplierMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblManageSupplierMouseExited(evt);
            }
        });
        jPanel2.add(lblManageSupplier, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 300, 60));

        lblManageCustomer.setBackground(new java.awt.Color(31, 40, 45));
        lblManageCustomer.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblManageCustomer.setForeground(new java.awt.Color(255, 255, 255));
        lblManageCustomer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/ijse/fms/images/customer.png"))); // NOI18N
        lblManageCustomer.setText(" [F2]      Manage Customer");
        lblManageCustomer.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        lblManageCustomer.setOpaque(true);
        lblManageCustomer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblManageCustomerMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblManageCustomerMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblManageCustomerMouseExited(evt);
            }
        });
        jPanel2.add(lblManageCustomer, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 300, 60));

        lblAddItem.setBackground(new java.awt.Color(31, 40, 45));
        lblAddItem.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblAddItem.setForeground(new java.awt.Color(255, 255, 255));
        lblAddItem.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblAddItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/ijse/fms/images/cart.png"))); // NOI18N
        lblAddItem.setText(" [F4]      Add Item");
        lblAddItem.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        lblAddItem.setOpaque(true);
        lblAddItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAddItemMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblAddItemMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblAddItemMouseExited(evt);
            }
        });
        jPanel2.add(lblAddItem, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 300, 60));

        lblGrn.setBackground(new java.awt.Color(31, 40, 45));
        lblGrn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblGrn.setForeground(new java.awt.Color(255, 255, 255));
        lblGrn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblGrn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/ijse/fms/images/grn.png"))); // NOI18N
        lblGrn.setText(" [F5]      GRN");
        lblGrn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        lblGrn.setOpaque(true);
        lblGrn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblGrnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblGrnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblGrnMouseExited(evt);
            }
        });
        jPanel2.add(lblGrn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 300, 60));

        lblLogOut.setBackground(new java.awt.Color(31, 40, 45));
        lblLogOut.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblLogOut.setForeground(new java.awt.Color(255, 255, 255));
        lblLogOut.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLogOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/ijse/fms/images/External_26px.png"))); // NOI18N
        lblLogOut.setText("LOG OUT");
        lblLogOut.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        lblLogOut.setOpaque(true);
        lblLogOut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblLogOutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblLogOutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblLogOutMouseExited(evt);
            }
        });
        jPanel2.add(lblLogOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 600, 300, 60));

        jLabel1.setBackground(new java.awt.Color(31, 40, 45));
        jLabel1.setOpaque(true);
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 660));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 300, 660));

        lblDate.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblDate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lblDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 230, 50));

        lblTime.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblTime.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jPanel1.add(lblTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(1044, 50, 310, 50));

        jLabel2.setBackground(new java.awt.Color(215, 222, 228));
        jLabel2.setAutoscrolls(true);
        jLabel2.setOpaque(true);
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 1370, 70));

        javax.swing.GroupLayout pnlItemLayout = new javax.swing.GroupLayout(pnlItem);
        pnlItem.setLayout(pnlItemLayout);
        pnlItemLayout.setHorizontalGroup(
            pnlItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 180, Short.MAX_VALUE)
        );
        pnlItemLayout.setVerticalGroup(
            pnlItemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );

        jPanel1.add(pnlItem, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pnlReport.setToolTipText("");

        javax.swing.GroupLayout pnlReportLayout = new javax.swing.GroupLayout(pnlReport);
        pnlReport.setLayout(pnlReportLayout);
        pnlReportLayout.setHorizontalGroup(
            pnlReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 181, Short.MAX_VALUE)
        );
        pnlReportLayout.setVerticalGroup(
            pnlReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 483, Short.MAX_VALUE)
        );

        jPanel1.add(pnlReport, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout MainPanelLayout = new javax.swing.GroupLayout(MainPanel);
        MainPanel.setLayout(MainPanelLayout);
        MainPanelLayout.setHorizontalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1070, Short.MAX_VALUE)
        );
        MainPanelLayout.setVerticalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 660, Short.MAX_VALUE)
        );

        jPanel1.add(MainPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 110, 1070, 660));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMouseClicked
        dispose();
    }//GEN-LAST:event_lblCloseMouseClicked

    private void lblCloseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMouseEntered
        lblClose.setBackground(new Color(255, 0, 0));
    }//GEN-LAST:event_lblCloseMouseEntered

    private void lblCloseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMouseExited
        lblClose.setBackground(new Color(40, 202, 204));
    }//GEN-LAST:event_lblCloseMouseExited

    private void lblSupplierOrderMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSupplierOrderMouseEntered
        lblSupplierOrder.setBackground(new Color(59, 62, 77));
    }//GEN-LAST:event_lblSupplierOrderMouseEntered

    private void lblSupplierOrderMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSupplierOrderMouseExited
        lblSupplierOrder.setBackground(new Color(31, 40, 45));
    }//GEN-LAST:event_lblSupplierOrderMouseExited

    private void lblViewReportsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblViewReportsMouseEntered
        lblViewReports.setBackground(new Color(59, 62, 77));

    }//GEN-LAST:event_lblViewReportsMouseEntered

    private void lblViewReportsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblViewReportsMouseExited
        lblViewReports.setBackground(new Color(31, 40, 45));

    }//GEN-LAST:event_lblViewReportsMouseExited

    private void lblManageUserMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblManageUserMouseEntered
        lblManageUser.setBackground(new Color(59, 62, 77));

    }//GEN-LAST:event_lblManageUserMouseEntered

    private void lblManageUserMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblManageUserMouseExited
        lblManageUser.setBackground(new Color(31, 40, 45));
    }//GEN-LAST:event_lblManageUserMouseExited

    private void lblManageSupplierMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblManageSupplierMouseEntered
        lblManageSupplier.setBackground(new Color(59, 62, 77));

    }//GEN-LAST:event_lblManageSupplierMouseEntered

    private void lblManageSupplierMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblManageSupplierMouseExited
        lblManageSupplier.setBackground(new Color(31, 40, 45));
    }//GEN-LAST:event_lblManageSupplierMouseExited

    private void lblManageCustomerMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblManageCustomerMouseEntered
        lblManageCustomer.setBackground(new Color(59, 62, 77));

    }//GEN-LAST:event_lblManageCustomerMouseEntered

    private void lblManageCustomerMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblManageCustomerMouseExited
        lblManageCustomer.setBackground(new Color(31, 40, 45));
    }//GEN-LAST:event_lblManageCustomerMouseExited

    private void lblClose1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblClose1MouseClicked
        dispose();
    }//GEN-LAST:event_lblClose1MouseClicked

    private void lblClose1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblClose1MouseEntered
        lblClose.setBackground(new Color(255, 0, 0));
    }//GEN-LAST:event_lblClose1MouseEntered

    private void lblClose1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblClose1MouseExited
        lblClose.setBackground(new Color(40, 202, 204));
    }//GEN-LAST:event_lblClose1MouseExited

    private void lblMinimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinimizeMouseClicked
        this.setState(1);
    }//GEN-LAST:event_lblMinimizeMouseClicked

    private void lblMinimizeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinimizeMouseEntered
        lblMinimize.setBackground(new Color(128, 169, 211));
    }//GEN-LAST:event_lblMinimizeMouseEntered

    private void lblMinimizeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinimizeMouseExited
        lblMinimize.setBackground(new Color(40, 202, 204));
    }//GEN-LAST:event_lblMinimizeMouseExited

    private void lblManageUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblManageUserMouseClicked
        manageUserPanel();
    }//GEN-LAST:event_lblManageUserMouseClicked

    private void lblManageCustomerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblManageCustomerMouseClicked
        manageCustomerPanel();

    }//GEN-LAST:event_lblManageCustomerMouseClicked

    private void lblManageSupplierMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblManageSupplierMouseClicked
        manageSupplierPanel();
    }//GEN-LAST:event_lblManageSupplierMouseClicked

    private void lblViewReportsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblViewReportsMouseClicked
       ReportsPanel report = new ReportsPanel(this);
       //  ReportsPanel report = new ReportsPanel();
        common();
        MainPanel.setLayout(null);
        pnlReport.setBounds(0, 360, 180, 480);
        pnlReport.add(report);
        MainPanel.add(pnlReport);
        report.setSize(pnlReport.getSize());


    }//GEN-LAST:event_lblViewReportsMouseClicked

    private void lblAddItemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAddItemMouseClicked

        manageAddItemPanel();
    }//GEN-LAST:event_lblAddItemMouseClicked

    private void lblAddItemMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAddItemMouseEntered
        lblAddItem.setBackground(new Color(59, 62, 77));
    }//GEN-LAST:event_lblAddItemMouseEntered

    private void lblAddItemMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAddItemMouseExited
        lblAddItem.setBackground(new Color(31, 40, 45));
    }//GEN-LAST:event_lblAddItemMouseExited

    private void lblGrnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblGrnMouseClicked
        new GRNFrame().setVisible(true);


    }//GEN-LAST:event_lblGrnMouseClicked

    private void lblSupplierOrderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSupplierOrderMouseClicked
        manageSupplierOrderPanel();
    }//GEN-LAST:event_lblSupplierOrderMouseClicked

    private void lblGrnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblGrnMouseEntered
        lblGrn.setBackground(new Color(59, 62, 77));       
    }//GEN-LAST:event_lblGrnMouseEntered

    private void lblGrnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblGrnMouseExited
       lblGrn.setBackground(new Color(31, 40, 45));
    }//GEN-LAST:event_lblGrnMouseExited

    private void lblLogOutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLogOutMouseClicked
       AdminMainFrame frame = new AdminMainFrame();
       dispose();
       NewLogin login = new  NewLogin();
       login.setVisible(true);
    }//GEN-LAST:event_lblLogOutMouseClicked

    private void lblLogOutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLogOutMouseEntered
       lblLogOut.setBackground(new Color(59, 62, 77));
    }//GEN-LAST:event_lblLogOutMouseEntered

    private void lblLogOutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLogOutMouseExited
       lblLogOut.setBackground(new Color(31, 40, 45));
    }//GEN-LAST:event_lblLogOutMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminMainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminMainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminMainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminMainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminMainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JPanel MainPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblAddItem;
    private javax.swing.JLabel lblClose;
    private javax.swing.JLabel lblClose1;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblGrn;
    private javax.swing.JLabel lblLogOut;
    private javax.swing.JLabel lblManageCustomer;
    private javax.swing.JLabel lblManageSupplier;
    private javax.swing.JLabel lblManageUser;
    private javax.swing.JLabel lblMinimize;
    private javax.swing.JLabel lblSupplierOrder;
    private javax.swing.JLabel lblTime;
    private javax.swing.JLabel lblViewReports;
    private javax.swing.JPanel pnlItem;
    private javax.swing.JPanel pnlReport;
    // End of variables declaration//GEN-END:variables

    private void common(){
        MainPanel.removeAll();
        MainPanel.repaint();
        MainPanel.revalidate();
    }

    public SupplierPanel createSupplierPanel(){
        if (supplierPanel == null) {
            supplierPanel = new SupplierPanel();
            return supplierPanel;
        } else {
            return supplierPanel;
        }
    }

    private UserPanel createUserPanel() {
        if (userPanel == null) {
            userPanel = new UserPanel();
            return userPanel;
        } else {
            return userPanel;
        }
    }

    private CustomerPanel createCustomerPanel() {
        if (customerPanel == null) {
            customerPanel = new CustomerPanel();
            return customerPanel;
        } else {
            return customerPanel;
        }
    }

    private AddItemPanel createAddItemPanel() {
        if (addItemPanel == null) {
            addItemPanel = new AddItemPanel();
            return addItemPanel;
        } else {
            return addItemPanel;
        }
    }

    private SupplierOrderPanel createSupplierOrderPanel() {
        if (supplierOrderPanel == null) {
            supplierOrderPanel = new SupplierOrderPanel();
            return supplierOrderPanel;
        } else {
            return supplierOrderPanel;
        }
    }

    private void manageSupplierOrderPanel() {
        SupplierOrderPanel supplierOrder = createSupplierOrderPanel();
        common();
        supplierOrder.setSize(MainPanel.getSize());
        MainPanel.add(supplierOrder);
    }

    private void manageAddItemPanel() {
        AddItemPanel addItem = createAddItemPanel();
        common();
        addItem.setSize(MainPanel.getSize());
        MainPanel.add(addItem);
    }

    private void manageSupplierPanel() {
        SupplierPanel supplier = createSupplierPanel();
        common();
        supplier.setSize(MainPanel.getSize());
        MainPanel.add(supplier);
    }

    private void manageUserPanel() {
        UserPanel user = createUserPanel();
        common();
        user.setSize(MainPanel.getSize());
        MainPanel.add(user);
    }

    private void manageCustomerPanel() {
        CustomerPanel customer = createCustomerPanel();
        common();
        customer.setSize(MainPanel.getSize());
        MainPanel.add(customer);
    }

    private void loadKeyListener() {
        KeyboardFocusManager manager = KeyboardFocusManager.getCurrentKeyboardFocusManager();
        manager.addKeyEventPostProcessor(new KeyEventPostProcessor() {

            @Override
            public boolean postProcessKeyEvent(KeyEvent e) {
                if (e.getID() == KeyEvent.KEY_PRESSED) {
                    switch (e.getKeyCode()) {
                        case KeyEvent.VK_F1:
                        manageUserPanel();break;
                        case KeyEvent.VK_F2:
                        manageCustomerPanel();break;
                        case KeyEvent.VK_F3:
                        manageSupplierPanel();break;
                        case KeyEvent.VK_F4:
                        manageAddItemPanel();break;
                        case KeyEvent.VK_F5:
                            ;break;
                        case KeyEvent.VK_F6:
                            manageSupplierOrderPanel();break;
                    }
                }
                return true;
            }

            
        });

    }
    public void time() {
        new Thread(() -> {
            while (true) {
                Date date = new Date();
                String currentdate = new SimpleDateFormat("hh:mm:ss aa").format(date);

                lblTime.setText(currentdate);
                try {
                    Thread.sleep(1000);
                } catch (InterruptedException ex) {

                }
            }
        }).start();
    }

public void date() {
        SimpleDateFormat sdf = new SimpleDateFormat("yyy-MM-dd");
        java.util.Date dd = new java.util.Date();
        String d = sdf.format(dd);
        lblDate.setText(d);
    }
}


