/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.ijse.fms.view;

import edu.ijse.fms.view.panel.CustomerOrderPanel;
import edu.ijse.fms.view.panel.CustomerPanel;
import edu.ijse.fms.view.panel.ViewAllItemPanel;
import java.awt.Color;
import java.awt.HeadlessException;
import java.text.SimpleDateFormat;
import java.util.Date;

/**
 *
 * @author Gnanod
 */
public class CashierMainFrame extends javax.swing.JFrame {

    /**
     * Creates new form CustomerMainFrame
     */
    private CustomerOrderPanel customerOrderPanel;
    private ViewAllItemPanel viewAllItemPanel;
    private static String userId;

    public CashierMainFrame()  {
    }
    
    
    public CashierMainFrame(String getType) {
        initComponents();
        userId =getType;
        time();
        date();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblMinimize1 = new javax.swing.JLabel();
        lblClose1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblDate = new javax.swing.JLabel();
        lblTime = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnViewItems = new javax.swing.JLabel();
        btnCustomerOrder = new javax.swing.JLabel();
        mainPanel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblMinimize1.setBackground(new java.awt.Color(40, 202, 204));
        lblMinimize1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblMinimize1.setText("  -");
        lblMinimize1.setOpaque(true);
        lblMinimize1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMinimize1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblMinimize1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblMinimize1MouseExited(evt);
            }
        });
        jPanel1.add(lblMinimize1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1290, 0, 40, 40));

        lblClose1.setBackground(new java.awt.Color(40, 202, 204));
        lblClose1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblClose1.setText("   X");
        lblClose1.setOpaque(true);
        lblClose1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblClose1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblClose1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblClose1MouseExited(evt);
            }
        });
        jPanel1.add(lblClose1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1330, 0, 40, 40));

        jLabel3.setBackground(new java.awt.Color(40, 202, 204));
        jLabel3.setOpaque(true);
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 40));

        lblDate.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblDate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(lblDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 230, 50));

        lblTime.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblTime.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jPanel1.add(lblTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(1044, 50, 310, 50));

        jPanel2.setBackground(new java.awt.Color(102, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnViewItems.setBackground(new java.awt.Color(31, 40, 45));
        btnViewItems.setDisplayedMnemonic('M');
        btnViewItems.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnViewItems.setForeground(new java.awt.Color(255, 255, 255));
        btnViewItems.setText("View Items");
        btnViewItems.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        btnViewItems.setOpaque(true);
        btnViewItems.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnViewItemsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnViewItemsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnViewItemsMouseExited(evt);
            }
        });
        jPanel2.add(btnViewItems, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 0, 169, 50));

        btnCustomerOrder.setBackground(new java.awt.Color(31, 40, 45));
        btnCustomerOrder.setDisplayedMnemonic('M');
        btnCustomerOrder.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnCustomerOrder.setForeground(new java.awt.Color(255, 255, 255));
        btnCustomerOrder.setText("  Customer Order");
        btnCustomerOrder.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        btnCustomerOrder.setOpaque(true);
        btnCustomerOrder.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCustomerOrderMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCustomerOrderMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCustomerOrderMouseExited(evt);
            }
        });
        jPanel2.add(btnCustomerOrder, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 169, 50));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 340, 50));

        mainPanel.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1370, Short.MAX_VALUE)
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 620, Short.MAX_VALUE)
        );

        jPanel1.add(mainPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 1370, 620));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setOpaque(true);
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 110, 1030, 50));

        jLabel1.setBackground(new java.awt.Color(102, 255, 255));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 780));

        jLabel2.setBackground(new java.awt.Color(215, 222, 228));
        jLabel2.setAutoscrolls(true);
        jLabel2.setOpaque(true);
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 1370, 70));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblClose1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblClose1MouseClicked
        dispose();
    }//GEN-LAST:event_lblClose1MouseClicked

    private void lblClose1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblClose1MouseEntered
        lblClose1.setBackground(new Color(255, 0, 0));
    }//GEN-LAST:event_lblClose1MouseEntered

    private void lblClose1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblClose1MouseExited
        lblClose1.setBackground(new Color(40, 202, 204));
    }//GEN-LAST:event_lblClose1MouseExited

    private void lblMinimize1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinimize1MouseClicked
        this.setState(1);
    }//GEN-LAST:event_lblMinimize1MouseClicked

    private void lblMinimize1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinimize1MouseEntered
        lblMinimize1.setBackground(new Color(128, 169, 211));
    }//GEN-LAST:event_lblMinimize1MouseEntered

    private void lblMinimize1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinimize1MouseExited
        lblMinimize1.setBackground(new Color(40, 202, 204));
    }//GEN-LAST:event_lblMinimize1MouseExited

    private void btnCustomerOrderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCustomerOrderMouseClicked
        customerCashierLoadPanel();

    }//GEN-LAST:event_btnCustomerOrderMouseClicked

    private void btnCustomerOrderMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCustomerOrderMouseEntered
        btnCustomerOrder.setBackground(new Color(59, 62, 77));
    }//GEN-LAST:event_btnCustomerOrderMouseEntered

    private void btnCustomerOrderMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCustomerOrderMouseExited
        btnCustomerOrder.setBackground(new Color(31, 40, 45));
    }//GEN-LAST:event_btnCustomerOrderMouseExited

    private void btnViewItemsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnViewItemsMouseClicked
        loadViewAllItemPanel();
    }//GEN-LAST:event_btnViewItemsMouseClicked

    private void btnViewItemsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnViewItemsMouseEntered
        btnViewItems.setBackground(new Color(59, 62, 77));
    }//GEN-LAST:event_btnViewItemsMouseEntered

    private void btnViewItemsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnViewItemsMouseExited
        btnViewItems.setBackground(new Color(31, 40, 45));
    }//GEN-LAST:event_btnViewItemsMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CashierMainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CashierMainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CashierMainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CashierMainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CashierMainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnCustomerOrder;
    private javax.swing.JLabel btnViewItems;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblClose1;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblMinimize1;
    private javax.swing.JLabel lblTime;
    private javax.swing.JPanel mainPanel;
    // End of variables declaration//GEN-END:variables

    public void time() {
        new Thread(() -> {
            while (true) {
                Date date = new Date();
                String currentdate = new SimpleDateFormat("hh:mm:ss aa").format(date);

                lblTime.setText(currentdate);
                try {
                    Thread.sleep(1000);
                } catch (InterruptedException ex) {

                }
            }
        }).start();
    }

    public void date() {
        SimpleDateFormat sdf = new SimpleDateFormat("yyy-MM-dd");
        java.util.Date dd = new java.util.Date();
        String d = sdf.format(dd);
        lblDate.setText(d);
    }

    public void customerCashierLoadPanel() {
        CustomerOrderPanel customer = loadCustomerPanel();
        common();
        customer.setSize(mainPanel.getSize());
        mainPanel.add(customer);
    }

    private void loadViewAllItemPanel() {
        ViewAllItemPanel pnl = loadPanel();
        common();
        pnl.setSize(mainPanel.getSize());
        mainPanel.add(pnl);
    }

    public CustomerOrderPanel loadCustomerPanel() {
        if (customerOrderPanel == null) {
            customerOrderPanel = new CustomerOrderPanel();
            return customerOrderPanel;
        } else {
            return customerOrderPanel;
        }
    }
     private ViewAllItemPanel loadPanel() {
        if (viewAllItemPanel == null) {
            viewAllItemPanel = new ViewAllItemPanel();
            return viewAllItemPanel;
        } else {
            return viewAllItemPanel;
        }
    }

    private void common() {
        mainPanel.removeAll();
        mainPanel.repaint();
        mainPanel.revalidate();
    }

   

}
