/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.ijse.fms.view;

/**
 *
 * @author Gnanod
 */
public class ChqueDetail extends javax.swing.JDialog {

    /**
     * Creates new form ChqueDetail
     */
    public ChqueDetail(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel34 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        txtSupplierId = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        txtSupplierId1 = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        txtSupplierId2 = new javax.swing.JTextField();
        txtSupplierId3 = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        btnCustomerSave = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel34.setBackground(new java.awt.Color(255, 255, 255));
        jLabel34.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(53, 126, 120));
        jLabel34.setText("Check Details");
        jLabel34.setToolTipText("");
        jLabel34.setOpaque(true);
        jPanel1.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, 200, 30));

        jLabel29.setBackground(new java.awt.Color(255, 255, 255));
        jLabel29.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(27, 157, 175));
        jLabel29.setText("Date");
        jLabel29.setToolTipText("");
        jLabel29.setOpaque(true);
        jLabel29.setRequestFocusEnabled(false);
        jPanel1.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 160, 30));

        txtSupplierId.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtSupplierId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSupplierIdActionPerformed(evt);
            }
        });
        txtSupplierId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSupplierIdKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSupplierIdKeyReleased(evt);
            }
        });
        jPanel1.add(txtSupplierId, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 220, 190, 30));

        jLabel30.setBackground(new java.awt.Color(255, 255, 255));
        jLabel30.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(27, 157, 175));
        jLabel30.setText("Customer Name");
        jLabel30.setToolTipText("");
        jLabel30.setOpaque(true);
        jLabel30.setRequestFocusEnabled(false);
        jPanel1.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 160, 30));

        txtSupplierId1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtSupplierId1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSupplierId1ActionPerformed(evt);
            }
        });
        txtSupplierId1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSupplierId1KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSupplierId1KeyReleased(evt);
            }
        });
        jPanel1.add(txtSupplierId1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, 190, 30));

        jLabel31.setBackground(new java.awt.Color(255, 255, 255));
        jLabel31.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(27, 157, 175));
        jLabel31.setText("Account Num");
        jLabel31.setToolTipText("");
        jLabel31.setOpaque(true);
        jLabel31.setRequestFocusEnabled(false);
        jPanel1.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 160, 30));

        txtSupplierId2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtSupplierId2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSupplierId2ActionPerformed(evt);
            }
        });
        txtSupplierId2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSupplierId2KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSupplierId2KeyReleased(evt);
            }
        });
        jPanel1.add(txtSupplierId2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, 190, 30));

        txtSupplierId3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtSupplierId3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSupplierId3ActionPerformed(evt);
            }
        });
        txtSupplierId3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSupplierId3KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSupplierId3KeyReleased(evt);
            }
        });
        jPanel1.add(txtSupplierId3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, 190, 30));

        jLabel32.setBackground(new java.awt.Color(255, 255, 255));
        jLabel32.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(27, 157, 175));
        jLabel32.setText("Cheq Number");
        jLabel32.setToolTipText("");
        jLabel32.setOpaque(true);
        jLabel32.setRequestFocusEnabled(false);
        jPanel1.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 160, 30));

        btnCustomerSave.setBackground(new java.awt.Color(255, 255, 255));
        btnCustomerSave.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnCustomerSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/ijse/fms/images/Add User Male_26px.png"))); // NOI18N
        btnCustomerSave.setText("Save");
        btnCustomerSave.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(27, 157, 175)));
        btnCustomerSave.setOpaque(true);
        btnCustomerSave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCustomerSaveMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCustomerSaveMouseEntered(evt);
            }
        });
        jPanel1.add(btnCustomerSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 270, 90, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtSupplierIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSupplierIdActionPerformed
//        String supplierCompanyName= txtSupplierCompanyName.getText();
//        if(supplierCompanyName.isEmpty()){
//            txtSupplierTelNumber.setBorder(new LineBorder(Color.red, 1));
//        }else{
//            txtSupplierTelNumber.setBorder(new LineBorder(Color.BLACK, 1));
//        }
    }//GEN-LAST:event_txtSupplierIdActionPerformed

    private void txtSupplierIdKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSupplierIdKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSupplierIdKeyPressed

    private void txtSupplierIdKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSupplierIdKeyReleased
//        String id = txtSupplierId.getText();
//        if(id.isEmpty()){
//            txtSupplierId.setBorder(new LineBorder(Color.red, 1));
//        }else{
//            txtSupplierId.setBorder(new LineBorder(Color.black, 1));
//        }
    }//GEN-LAST:event_txtSupplierIdKeyReleased

    private void txtSupplierId1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSupplierId1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSupplierId1ActionPerformed

    private void txtSupplierId1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSupplierId1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSupplierId1KeyPressed

    private void txtSupplierId1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSupplierId1KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSupplierId1KeyReleased

    private void txtSupplierId2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSupplierId2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSupplierId2ActionPerformed

    private void txtSupplierId2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSupplierId2KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSupplierId2KeyPressed

    private void txtSupplierId2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSupplierId2KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSupplierId2KeyReleased

    private void txtSupplierId3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSupplierId3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSupplierId3ActionPerformed

    private void txtSupplierId3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSupplierId3KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSupplierId3KeyPressed

    private void txtSupplierId3KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSupplierId3KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSupplierId3KeyReleased

    private void btnCustomerSaveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCustomerSaveMouseClicked
//        String customerId = txtCustomerId.getText();
//        String customerName = txtCustomerName.getText();
//        String customerGender = "male";
//
//        if (btnCustomerMale.isSelected()) {
//            customerGender = "male";
//        }
//        if (btnCustomerFemale.isSelected()) {
//            customerGender = "Female";
//        }
//        String customerTelNumber = txtCustomerTelNumber.getText();
//        String customerAddress = txtCustomerAddress.getText();
//        CustomerDTO customerDto = new CustomerDTO(customerId, customerName, customerGender, customerTelNumber, customerAddress);
//        if (customerId.isEmpty()) {
//            txtCustomerId.setBorder(new LineBorder(Color.red, 1));
//        }
//        if (customerName.isEmpty()) {
//            txtCustomerName.setBorder(new LineBorder(Color.red, 1));
//        }
//        if (!customerTelNumber.matches("\\d{3}-\\d{7}")) {
//            txtCustomerTelNumber.setBorder(new LineBorder(Color.red, 1));
//        }
//        if (customerAddress.isEmpty()) {
//            txtCustomerAddress.setBorder(new LineBorder(Color.red, 1));
//        }
//        if (customerId.isEmpty() == false && customerName.isEmpty() == false && customerTelNumber.matches("\\d{3}-\\d{7}") == false && customerAddress.isEmpty() == false) {
//            try {
//                boolean isAdded = customerController.add(customerDto);
//                System.out.println(isAdded);
//                if (isAdded) {
//                    JOptionPane.showMessageDialog(this, "Added Sucessfully");
//                    textFieldNull();
//                    getID();
//                } else {
//                    JOptionPane.showMessageDialog(this, "Oops Added Fail", "Error", JOptionPane.ERROR_MESSAGE);
//                }
//            } catch (SQLException ex) {
//                String errorMsg;
//                switch (ex.getErrorCode()){
//                    case 1062:
//                    errorMsg = "Duplicate entry has been found. Please enter valid Customer Id to proceed.";
//                    break;
//                    default:
//                    errorMsg = "Customer has been failed to add";
//                    break;
//                }
//                JOptionPane.showMessageDialog(this, errorMsg, "Error", JOptionPane.ERROR_MESSAGE);
//
//            } catch (Exception ex) {
//                Logger.getLogger(CustomerPanel.class.getName()).log(Level.SEVERE, null, ex);
//            }
//
//        }

    }//GEN-LAST:event_btnCustomerSaveMouseClicked

    private void btnCustomerSaveMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCustomerSaveMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCustomerSaveMouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChqueDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChqueDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChqueDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChqueDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ChqueDetail dialog = new ChqueDetail(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnCustomerSave;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtSupplierId;
    private javax.swing.JTextField txtSupplierId1;
    private javax.swing.JTextField txtSupplierId2;
    private javax.swing.JTextField txtSupplierId3;
    // End of variables declaration//GEN-END:variables
}
