/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.ijse.fms.view;

import javax.swing.UIManager;

/**
 *
 * @author Gnanod
 */
public class CreditCardDetail extends javax.swing.JDialog {

    /**
     * Creates new form CreditCardDetail
     */
    public CreditCardDetail(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel34 = new javax.swing.JLabel();
        btnCustomerSave = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel34.setBackground(new java.awt.Color(255, 255, 255));
        jLabel34.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(53, 126, 120));
        jLabel34.setText("Check Details");
        jLabel34.setToolTipText("");
        jLabel34.setOpaque(true);
        getContentPane().add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 200, 30));

        btnCustomerSave.setBackground(new java.awt.Color(255, 255, 255));
        btnCustomerSave.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnCustomerSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/ijse/fms/images/Add User Male_26px.png"))); // NOI18N
        btnCustomerSave.setText("Save");
        btnCustomerSave.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(27, 157, 175)));
        btnCustomerSave.setOpaque(true);
        btnCustomerSave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCustomerSaveMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCustomerSaveMouseEntered(evt);
            }
        });
        getContentPane().add(btnCustomerSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 270, 90, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCustomerSaveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCustomerSaveMouseClicked
        //        String customerId = txtCustomerId.getText();
        //        String customerName = txtCustomerName.getText();
        //        String customerGender = "male";
        //
        //        if (btnCustomerMale.isSelected()) {
            //            customerGender = "male";
            //        }
        //        if (btnCustomerFemale.isSelected()) {
            //            customerGender = "Female";
            //        }
        //        String customerTelNumber = txtCustomerTelNumber.getText();
        //        String customerAddress = txtCustomerAddress.getText();
        //        CustomerDTO customerDto = new CustomerDTO(customerId, customerName, customerGender, customerTelNumber, customerAddress);
        //        if (customerId.isEmpty()) {
            //            txtCustomerId.setBorder(new LineBorder(Color.red, 1));
            //        }
        //        if (customerName.isEmpty()) {
            //            txtCustomerName.setBorder(new LineBorder(Color.red, 1));
            //        }
        //        if (!customerTelNumber.matches("\\d{3}-\\d{7}")) {
            //            txtCustomerTelNumber.setBorder(new LineBorder(Color.red, 1));
            //        }
        //        if (customerAddress.isEmpty()) {
            //            txtCustomerAddress.setBorder(new LineBorder(Color.red, 1));
            //        }
        //        if (customerId.isEmpty() == false && customerName.isEmpty() == false && customerTelNumber.matches("\\d{3}-\\d{7}") == false && customerAddress.isEmpty() == false) {
            //            try {
                //                boolean isAdded = customerController.add(customerDto);
                //                System.out.println(isAdded);
                //                if (isAdded) {
                    //                    JOptionPane.showMessageDialog(this, "Added Sucessfully");
                    //                    textFieldNull();
                    //                    getID();
                    //                } else {
                    //                    JOptionPane.showMessageDialog(this, "Oops Added Fail", "Error", JOptionPane.ERROR_MESSAGE);
                    //                }
                //            } catch (SQLException ex) {
                //                String errorMsg;
                //                switch (ex.getErrorCode()){
                    //                    case 1062:
                    //                    errorMsg = "Duplicate entry has been found. Please enter valid Customer Id to proceed.";
                    //                    break;
                    //                    default:
                    //                    errorMsg = "Customer has been failed to add";
                    //                    break;
                    //                }
                //                JOptionPane.showMessageDialog(this, errorMsg, "Error", JOptionPane.ERROR_MESSAGE);
                //
                //            } catch (Exception ex) {
                //                Logger.getLogger(CustomerPanel.class.getName()).log(Level.SEVERE, null, ex);
                //            }
            //
            //        }
    }//GEN-LAST:event_btnCustomerSaveMouseClicked

    private void btnCustomerSaveMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCustomerSaveMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCustomerSaveMouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
            //UIManager.setLookAndFeel("new com.jtattoo.plaf.acryl.AcrylLookAndFeel");
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreditCardDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreditCardDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreditCardDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreditCardDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CreditCardDetail dialog = new CreditCardDetail(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnCustomerSave;
    private javax.swing.JLabel jLabel34;
    // End of variables declaration//GEN-END:variables
}
