package edu.ijse.fms.view;

import edu.ijse.fms.controller.ControllerFactory;
import edu.ijse.fms.controller.custom.UserController;
import edu.ijse.fms.dto.UserDTO;
import edu.ijse.fms.view.AdminMainFrame;
import edu.ijse.fms.view.CashierMainFrame;
import java.awt.Color;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Gnanod
 */
public class NewLogin extends javax.swing.JFrame {

    /**
     * Creates new form NewLogin
     */
    private UserController userController;
    private UserDTO search;
    private String password;

    public NewLogin() {
        initComponents();
        userController = (UserController) ControllerFactory.getInstance().getController(ControllerFactory.ControllerTypes.USER);
        lblPasswordIncorret.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblPasswordIncorret = new javax.swing.JLabel();
        txtUserPassword = new javax.swing.JPasswordField();
        cmbUserType = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        txtUserName = new org.jdesktop.swingx.JXSearchField();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jLabel3.setOpaque(true);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(550, 50));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblPasswordIncorret.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        lblPasswordIncorret.setForeground(new java.awt.Color(204, 0, 0));
        lblPasswordIncorret.setText("The Password that you've enterd incorrect");
        jPanel1.add(lblPasswordIncorret, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 310, 270, 30));

        txtUserPassword.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtUserPassword.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 132, 255)));
        txtUserPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtUserPasswordKeyReleased(evt);
            }
        });
        jPanel1.add(txtUserPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 270, 270, 40));

        cmbUserType.setEditable(true);
        cmbUserType.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cmbUserType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Administrator", "Cashier" }));
        cmbUserType.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 132, 255)));
        jPanel1.add(cmbUserType, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, 270, 40));

        jLabel2.setBackground(new java.awt.Color(116, 46, 204));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("LOGIN");
        jLabel2.setOpaque(true);
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 340, 270, 40));

        txtUserName.setPrompt("UserId");
        jPanel1.add(txtUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 220, 270, 40));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Login");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 100, 160, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edu/ijse/fms/images/Login.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 440));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtUserPasswordKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUserPasswordKeyReleased
//        if (search.getUserPassword().equals(password)) {
//            lblPasswordIncorret.setVisible(false);
//
//        } else {
////                        
//            lblPasswordIncorret.setVisible(true);
//        }
    }//GEN-LAST:event_txtUserPasswordKeyReleased

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        try {
            String userType = (String) cmbUserType.getSelectedItem();
            String name = txtUserName.getText();
            String id = txtUserName.getText();
            password = txtUserPassword.getText();
//            String [] user = {userType,name,password};
            search = userController.search(id);
            if (search != null) {
                String getId = search.getUserId();
                String type = search.getUserType();
                if (type.equals("Administrator")) {
                    if (search.getUserPassword().equals(password)) {

                        AdminMainFrame adminMainFrame = new AdminMainFrame(type);
                        this.dispose();
                        adminMainFrame.setVisible(true);
                    } else {
//                        JOptionPane.showMessageDialog(this, "Sorry Wrong Details");
                        lblPasswordIncorret.setVisible(true);
                    }

                } else {
                    CashierMainFrame cashier = new CashierMainFrame(type);
                    cashier.setVisible(true);
                }
            }
        } catch (Exception ex) {
            Logger.getLogger(NewLogin.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jLabel2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox cmbUserType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblPasswordIncorret;
    private org.jdesktop.swingx.JXSearchField txtUserName;
    private javax.swing.JPasswordField txtUserPassword;
    // End of variables declaration//GEN-END:variables
}
